#!/usr/bin/env python3
"""Regenerate ROOT.sexp from the canonical modules (deterministic). ROOT pins the exact module set, each module's
SHA-256, the canonical model-root digest, the parent architecture commit and the schema version. A manual edit of a
module without re-running this makes the kernel's L7 (exact file/module/hash universe) fail."""
import os, hashlib, glob
HERE=os.path.dirname(os.path.abspath(__file__))
# PINNED migration baseline = the architecture commit this model was migrated FROM. This is a CONSTANT, never the
# live git HEAD: once this change is committed HEAD moves, and a fresh clone must regenerate ROOT.sexp byte-
# identically (gate 07). Reading HEAD here would make the parent field non-reproducible across clones.
PARENT_ARCHITECTURE_COMMIT='4787b342282f8d5f2ec4b9e64b11e32b7a64813a'
# The module universe is DISCOVERED (every *.sexp in this dir except ROOT.sexp), so a new module can never be
# silently dropped from the hash-root. Deterministic order = sorted basenames. Kernel law L7 re-checks that the
# pinned set exactly equals the on-disk set (no extra, none missing).
MODULES=sorted(os.path.basename(p) for p in glob.glob(os.path.join(HERE,'*.sexp'))
               if os.path.basename(p)!='ROOT.sexp')
# ONE hashing definition on every path of this model (see TOOLCHAIN.sexp):
#   hash(file)   = SHA-256 over the EXACT RAW BYTES of the file — no decoding, no newline translation, no
#                  error replacement (a byte that is not valid UTF-8 must change the digest, not vanish);
#   hash(string) = SHA-256 over the UTF-8 encoding of the string.
# The Common Lisp path computes the same two functions with a different vetted engine (ironclad).
def sha(fn):
    with open(os.path.join(HERE,fn),'rb') as f:
        return hashlib.sha256(f.read()).hexdigest()
# The schema version is READ from the schema module — one seat. A schema change that forgot to update ROOT
# would otherwise leave the root advertising a version the model no longer has.
def read_schema_version():
    txt=open(os.path.join(HERE,'MODEL-SCHEMA.sexp'),encoding='utf-8').read()
    k=txt.index('define-model-schema')
    j=txt.index(':version',k); a=txt.index('"',j)+1; b=txt.index('"',a)
    return txt[a:b]
schema_version=read_schema_version()
parent=PARENT_ARCHITECTURE_COMMIT
rows=[(m,sha(m)) for m in MODULES]
root_digest=hashlib.sha256('\n'.join('%s:%s'%(m,h) for m,h in rows).encode('utf-8')).hexdigest()
lines=[';;;; ROOT.sexp — hash-root of the canonical ARCHITECTURE-MODEL. GENERATED by build_root.py (deterministic).',
       ';;;; Pins the EXACT module set, each module SHA-256, the canonical model-root digest, the parent architecture',
       ';;;; commit and the schema version. Editing a module without re-running build_root.py makes kernel law L7 fail.',
       '(define-model-root architecture-model',
       '  :model-version "1"',
       '  :schema-version "%s"'%schema_version,
       '  :parent-architecture-commit "%s"'%parent,
       '  :canonical-model-root-digest "%s"'%root_digest,
       '  :module-count %d'%len(rows),
       '  :composition (']
for m,h in rows:
    lines.append('    (:module "%s" :sha256 "%s")'%(m,h))
lines.append('  ))')
open(os.path.join(HERE,'ROOT.sexp'),'w',encoding='utf-8',newline='\n').write('\n'.join(lines)+'\n')
print('ROOT.sexp written: %d modules, root-digest %s parent %s'%(len(rows),root_digest[:16],parent[:12]))
