#!/usr/bin/env python3
"""Regenerate ROOT.sexp from the canonical modules (deterministic).

ROOT pins the exact module set, each module's SHA-256, the canonical model-root digest, the parent architecture
commit and the schema version. A manual edit of a module without re-running this makes kernel law L7 fail.

Review-2 N-16: the schema version is no longer extracted with `txt.index(':version')` and a pair of quote
offsets. That was an undeclared second reader of canonical structure — it would have silently produced the wrong
version if a comment above the form had mentioned `define-model-schema`, and nothing validated the value it
produced. The version now comes from the ONE classified reader seat (SEXP-READER.py) through a typed structural
lookup that rejects a missing, duplicated, malformed or surplus schema declaration, and the kernel and the
independent checker both re-derive it and require ROOT to bind exactly that value.

Review-2 N-2: `--out DIR` writes the regenerated ROOT somewhere else and leaves the committed module untouched,
so the gate can COMPARE instead of overwrite. Without it the file is written in place, which is what the
separate `regenerate.py` apply command does.
"""
import argparse, hashlib, importlib.util, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location('sexp_reader', os.path.join(HERE, 'SEXP-READER.py'))
SR = importlib.util.module_from_spec(_spec); _spec.loader.exec_module(SR)

# PINNED migration baseline = the architecture commit this model was migrated FROM. This is a CONSTANT, never the
# live git HEAD: once this change is committed HEAD moves, and a fresh clone must regenerate ROOT.sexp
# byte-identically. Reading HEAD here would make the parent field non-reproducible across clones.
PARENT_ARCHITECTURE_COMMIT = '4787b342282f8d5f2ec4b9e64b11e32b7a64813a'


def sha_file(path):
    """ONE hashing definition on every path of this model: SHA-256 over the exact raw bytes."""
    with open(path, 'rb') as f:
        return hashlib.sha256(f.read()).hexdigest()


def schema_version():
    """The schema's declared version, read structurally under the one canonical rule of the reader seat
    (Review-5 §5.2): a missing, duplicated, malformed or surplus declaration, an unquoted integer, a leading
    zero or a non-ASCII digit is a typed failure here, exactly as it is in the gate."""
    forms = SR.read_forms_file(os.path.join(HERE, 'MODEL-SCHEMA.sexp'))
    return SR.schema_version_of(SR.schema_declaration(forms))


def modules():
    """The module universe is DISCOVERED — every *.sexp beside ROOT.sexp — so a new module can never be silently
    dropped from the hash root. Deterministic order = sorted basenames; kernel law L7 re-checks that the pinned
    set exactly equals the on-disk set (no extra, none missing)."""
    return sorted(n for n in os.listdir(HERE) if n.endswith('.sexp') and n != 'ROOT.sexp')


def render(mods, version):
    rows = [(m, sha_file(os.path.join(HERE, m))) for m in mods]
    digest = SR.root_digest(rows)          # the ONE formula, shared with the loader that verifies it
    out = [';;;; ROOT.sexp — hash-root of the canonical ARCHITECTURE-MODEL. GENERATED by build_root.py (deterministic).',
           ';;;; Pins the EXACT module set, each module SHA-256, the canonical model-root digest, the parent architecture',
           ';;;; commit and the schema version. Editing a module without re-running build_root.py makes kernel law L7 fail.',
           ';;;; Review-2 N-9: this file is held to the same complete-consumption discipline as every module — exactly one',
           ';;;; top-level form, no duplicate plist key, a schema version that must equal MODEL-SCHEMA.sexp\'s own, and a',
           ';;;; well-formed 40-character parent commit. Both verification paths enforce all of it.',
           '(define-model-root architecture-model',
           '  :model-version "1"',
           '  :schema-version "%s"' % version,
           '  :parent-architecture-commit "%s"' % PARENT_ARCHITECTURE_COMMIT,
           '  :canonical-model-root-digest "%s"' % digest,
           '  :module-count %d' % len(rows),
           '  :composition (']
    out += ['    (:module "%s" :sha256 "%s")' % r for r in rows]
    out.append('  ))')
    return '\n'.join(out) + '\n', digest, len(rows)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--out', help='write the regenerated ROOT.sexp into this directory instead of in place')
    args = ap.parse_args()
    try:
        version = schema_version()
        text, digest, n = render(modules(), version)
    except SR.SexpError as e:
        sys.stderr.write('%s\n' % e)
        sys.exit(2)
    target = os.path.join(args.out if args.out else HERE, 'ROOT.sexp')
    with open(target, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('ROOT.sexp written: %d modules, schema-version %s, root-digest %s parent %s'
          % (n, version, digest[:16], PARENT_ARCHITECTURE_COMMIT[:12]))


if __name__ == '__main__':
    main()
