;;;; ROOT.sexp — hash-root of the canonical ARCHITECTURE-MODEL. GENERATED by build_root.py (deterministic).
;;;; Pins the EXACT module set, each module SHA-256, the canonical model-root digest, the parent architecture
;;;; commit and the schema version. Editing a module without re-running build_root.py makes kernel law L7 fail.
;;;; Review-2 N-9: this file is held to the same complete-consumption discipline as every module — exactly one
;;;; top-level form, no duplicate plist key, a schema version that must equal MODEL-SCHEMA.sexp's own, and a
;;;; well-formed 40-character parent commit. Both verification paths enforce all of it.
(define-model-root architecture-model
  :model-version "1"
  :schema-version "3"
  :parent-architecture-commit "4787b342282f8d5f2ec4b9e64b11e32b7a64813a"
  :canonical-model-root-digest "46bf277330e42ef431350ae96d7bb845b755ae6e157b88587cf3a21d46f9f5ce"
  :module-count 13
  :composition (
    (:module "MODEL-SCHEMA.sexp" :sha256 "e649d5f8cac15585b3cdf91fc42a3a92d5771473748894f25e52b8ac48d5848b")
    (:module "TOOLCHAIN.sexp" :sha256 "edc3e7575d6cf00caf4a80ed84f2335d8fdb500575c197ed038571c41ebab216")
    (:module "deferred-imports.sexp" :sha256 "292067c5d78525a9777efa45fa380c6320bd7c91671da7e35d39fca2abb48177")
    (:module "dependencies-and-boundaries.sexp" :sha256 "132d074c4ae6adda39ff00d239983f9d73b6fffa5b93ee9c6c74ff87d6a6bc16")
    (:module "files-and-roles.sexp" :sha256 "4e00e7b44e1f6663f1f81e7e899a428af10fed2fa7c5f80938aa15e07de7fcb3")
    (:module "generation-order.sexp" :sha256 "bede6968851351fbdacc30a76cd5c89ba105d0957cdc4ad1f0ca4a4aed200128")
    (:module "interfaces-and-types.sexp" :sha256 "d809def3283a3f4a802d37aebeaf75cc3367b02bae0360b2869a40d6eb9f95a5")
    (:module "rationale-references.sexp" :sha256 "c39888e27c03723205238798e334e34f7fe93da5ca8217a583537154e37569ec")
    (:module "requirements-tests-workpackets.sexp" :sha256 "1702ef0fa51f3d091f0b8b6c430979b18b25c60cfabc16a0ea20f79de54c3b1e")
    (:module "seats.sexp" :sha256 "5a220af64cf4e0deb1b45e7819923e251b17dd46bc5450c94413bfa907347fa9")
    (:module "stores-and-authorities.sexp" :sha256 "5ed5c95450bbda902ef350d77bed924bd4ef9ab0938a101c469a7f920ba35b60")
    (:module "subsystems.sexp" :sha256 "f3c7ea6634b6e3ad280afc68544247fef4b6fa96a4fd0bc86cd46d03c22ad18f")
    (:module "verification-corpus.sexp" :sha256 "85d727c8af862d767509bb0bb80dc36d656a63f13af9b1d7ed5de59c610363f2")
  ))
