;;;; stores-and-authorities.sexp — one fact per store (single owner + single writer, L2)
;;;; GENERATED BY MIGRATION build_model.py FROM v1.6-v1.8 REGISTRIES — thereafter EDIT HERE (canonical).
;;;; Uniform fact form: (fact <type> <id> :key value ...). No eval. Read with *read-eval* nil.

(fact store citation-observatory :owner SEAT-CITATION-AUTHORITY :writer SEAT-OBSERVATORY-COLLECTOR)
(fact store coverage-ledger :owner SEAT-COVERAGE-LEDGER :writer SEAT-COVERAGE-OWNER)
(fact store dataset-distribution :owner SEAT-AI-CORPUS-DUMP :writer SEAT-RA-T-SIGNER)
(fact store journal :owner SEAT-JOURNAL :writer SEAT-WRITE-AUTHORITY)
(fact store legal-ir :owner SEAT-LEGAL-AST :writer SEAT-WRITE-AUTHORITY)
(fact store memory :owner SEAT-MEMORY :writer SEAT-WRITE-AUTHORITY)
(fact store resolver-dataset :owner SEAT-CANONICAL-URIS :writer SEAT-NO-WRITER)
(fact store static-site :owner SEAT-STATIC-SITE :writer SEAT-NO-WRITER)
(fact store tenant-profile :owner SEAT-TENANT-PROFILE :writer SEAT-NO-WRITER)
(fact store trust-bundle :owner SEAT-KERNEL-VERIFY :writer SEAT-MLTP-THRESHOLD-CUSTODY)
