;;;; stores-and-authorities.sexp — one fact per store (single owner + single writer, L2)
;;;; GENERATED BY MIGRATION build_model.py FROM v1.6-v1.8 REGISTRIES — thereafter EDIT HERE (canonical).
;;;; Uniform fact form: (fact <type> <id> :key value ...). No eval. Read with *read-eval* nil.

(fact store citation-observatory :owner "WP-13 citation-authority.lisp" :writer observatory-collector)
(fact store coverage-ledger :owner "WP-01 coverage-ledger.lisp[design-target]" :writer coverage-owner)
(fact store dataset-distribution :owner "WP-11 ai-corpus-dump.lisp" :writer RA-T-signer)
(fact store journal :owner "WP-03 journal.lisp" :writer write-authority.lisp)
(fact store legal-ir :owner "WP-03 legal-ast.lisp" :writer write-authority.lisp)
(fact store memory :owner memory.lisp :writer write-authority.lisp)
(fact store resolver-dataset :owner "RA-S25 canonical-uris.lisp" :writer none)
(fact store static-site :owner "WP-12 static-site.lisp" :writer none)
(fact store tenant-profile :owner "RA-S26 [interface-only]" :writer none)
(fact store trust-bundle :owner "WP-06 MLTP-root" :writer MLTP-threshold-custody)
