#!/usr/bin/env python3
# Build _ssp_freeze_v2.json from _ssp_freeze.json per reconciliation of the three adversarial critiques.
import json, collections

BASE = "/tmp/claude-0/-home-user-THE-LEGAL-WATCHTOWER/8a568901-aaa2-51c4-86b4-eb7bbdff4e90/scratchpad"
v1 = json.load(open(f"{BASE}/_ssp_freeze.json"), object_pairs_hook=collections.OrderedDict)
v2 = collections.OrderedDict()
v2["instrument_version"] = "2.0.0"

v2["order_definition"] = (
    "Design-stage dominance order >=_T over candidate architectures, defined purely on the 22 frozen axis lattices and the hard invariants H1-H8. "
    "HONEST INDEPENDENCE STATEMENT (v2): this frozen instrument contains ONLY design-neutral guarantee statements and derivation obligations; every attainment witness — including any reference to B0 files or to any existing design's seats — lives in a separate, NON-FROZEN attainment-witness appendix that is not part of this instrument, carries no normative force, and never enters rank assignment. The v1 claim 'with no reference to any existing design' held for the ladders except two tailored rungs (AX-10 R4; AX-07/AX-12 R3), which v2 restates in guarantee terms under incomparable_rule S2; mechanism examples in appendices may be biased toward known designs, and that bias is acknowledged, not denied. "
    "For each axis AX-k a frozen, totally ordered ladder of typed guarantee ranks L_k is fixed BEFORE any candidate is examined (see axis_lattices). rank_k(X) is the highest rung of L_k for which independently re-checkable evidence exists for candidate X (H8: recompute-and-compare, never a declared root); absent such evidence the axis is typed UNKNOWN (H2), never estimated. "
    "NEW IN v2 — KNOWN_UPPER_BOUND (cap): for a closed or external candidate X whose internals are unavailable, cap_k(X) <= R_n may be established without access to X by (i) a reproducible behavioral counterexample — an independently re-runnable demonstration that X fails a criterion of rung R_{n+1} — or (ii) a declared-mechanism-class argument: even taking X's declared mechanism at face value (the candidate's best case), that mechanism class attains at most R_n on the frozen ladder. Vendor-declared or secondary-relayed material (evidence status VERIFIED_FROM_SECONDARY) NEVER grounds a rank; it grounds at most a cap via (ii). A cap is not a rank and not an exit from UNKNOWN: rank_k(X) remains UNKNOWN, bounded above by cap_k(X). Caps operate only AGAINST the capped candidate: they may support dominance over X, never X's advancement, a TIE, or a win by X. "
    "Definition: A >=_T B iff (i) for EVERY axis k in {AX-01..AX-22}, either rank_k(A) and rank_k(B) are both KNOWN with rank_k(A) >= rank_k(B) in L_k, or rank_k(A) is KNOWN and rank_k(B) carries cap_k(B) with rank_k(A) >= cap_k(B) (sound because rank_k(B) <= cap_k(B) by construction); and (ii) no axis is INCOMPARABLE between A and B. Strict dominance A >_T B additionally requires at least one axis k where the gap satisfies that axis's pre-registered delta_rule (>= 1 full rank, class-level for AX-17/18), computed against rank_k(B) when KNOWN or against cap_k(B) when capped. "
    "The order is strictly NON-COMPENSATORY: comparison is the per-axis product order only — a strict advantage on any number of axes NEVER offsets a strict deficit on even one axis; there is no weighting, no summation, no averaging, no score, and no aggregate object anywhere in the instrument (compensation is structurally impossible because no field exists to hold it, per verdict_schema). "
    "Consequences: if A is strictly better on some axes and strictly worse on others, A and B are INCOMPARABLE under >=_T (see incomparable_rule: synthesis obligation, never a coin-flip). If any axis of either candidate is UNKNOWN, no >=_T, TIE, or equality verdict may issue on the pair EXCEPT (v2) a conclusion decided via a valid cap comparison or carrying a certified invariance (stability) certificate per unknown_rule — in both cases the conclusion is a proof, not a presumption; otherwise UNKNOWN blocks, fail-closed (H3). "
    "Rank assignment is itself a trusted derivation: pure, deterministic, from frozen evidence artifacts, offline re-verifiable by third parties (H5, H8); an assessor's unverifiable claim of a rank is not a rank, and no rank-grade language ('at ceiling grade', 'supreme-grade', 'attained') may appear in any frozen derivation — such statements are hypotheses that live only in the non-frozen attainment appendix, typed UNKNOWN until independently replayed. "
    "Equality on an axis (TIE) requires both ranks KNOWN and equal — UNKNOWN never upgrades to TIE or pass (H2), and a cap never grounds a TIE. This order is total in type but partial in fact: incomparability and unknownness are first-class outcomes, and the tournament may only conclude via the termination_rule, never by exhausting comparisons."
)

# ---- axis lattice patches ----
axes = {a["axis_id"]: a for a in v1["axis_lattices"]}

# AX-01: R5 raised to certified unique-status semantics above grounded (S2 refinement).
axes["AX-01"]["rank_levels"][4] = (
    "R5 certified-unique-status-defeater-closed: every answer carries an offline re-checkable proof object computed under a certified UNIQUE-STATUS semantics STRICTLY STRONGER than grounded acceptance — ideal or eager semantics, or sceptical acceptance under preferred semantics with a certified exhaustive-extension search — each per-query unique and deterministic (H5) and decidable over the finite admitted base (H3); the proof object includes a certified exhaustive defeater search over the admitted base, and absence-of-defeater is itself certified or the answer is typed UNKNOWN; polynomial-time computability is NOT a rank criterion — the semantics' declared complexity class is governed under AX-17 — so a grounded-only proof-carrying system satisfies every R5 criterion except semantics strength and scores R4 with the semantics gap recorded"
)
axes["AX-01"]["delta_rule"] += (
    " v2 (S2 refinement, version-stamped): R5 was RAISED to reflect the true ceiling — certified unique-status semantics above grounded (ideal/eager, sceptical-preferred with certified enumeration are unique, deterministic, and decidable on the finite committed base; only polynomial time is lost, and P-time is not an H1-H8 invariant); all prior AX-01 verdicts are invalidated and must be re-adjudicated under this ladder."
)

# AX-07: R3 + delta de-tailored to single canonical serialization point; H4 operative content frozen.
axes["AX-07"]["rank_levels"][2] = (
    "R3 canonical-matter-state: canonical typed matter record with a single canonical serialization point — physical single writer OR consensus-established logical writer with machine-checked nonforking — under capability closure (H4), whose operative content is frozen design-neutrally: a write becomes canonical only by passing the single decidable admission predicate BEFORE canonicalization at that serialization point; reads deterministic"
)
axes["AX-07"]["delta_rule"] = (
    "Strict gap iff rank_A >= rank_B + 1 on this frozen ladder; R3+ requires evidence that the single-canonical-serialization-point property (physical single writer, or consensus-established logical writer with machine-checked nonforking) is structurally enforced, not conventionally observed."
)

# AX-09: stability-certificate interplay note.
axes["AX-09"]["delta_rule"] += (
    " v2: a derived verdict carrying a certified invariance (stability) certificate per unknown_rule(4) — machine-checked, quantifying over ALL completions of the UNKNOWN inputs it ranges over, offline re-checkable — is a KNOWN certified outcome of this axis's frontier accounting, fully compatible with H2 (it is quantification over completions, not guessing); absent the certificate the derived verdict is UNKNOWN."
)

# AX-10: R4 de-tailored to guarantee terms.
axes["AX-10"]["rank_levels"][3] = (
    "R4 institutional-counter-design: structurally independent adversarial review — fresh context, no access to implementer rationale — is a blocking admission gate; every finding reaches a recorded, append-only-auditable terminal disposition: fixed at its point of origin, refuted with recorded proof, or tracked to a scheduled removal"
)

# AX-12: R3 de-tailored, same serialization-point guarantee wording.
axes["AX-12"]["rank_levels"][2] = (
    "R3 capability-gated-transitions: every state transition requires a capability-checked authority under capability closure (H4), read design-neutrally: the transition becomes canonical only by passing the single decidable admission predicate BEFORE canonicalization at a single canonical serialization point (physical single writer OR consensus-established logical writer with machine-checked nonforking); unauthorized attempts rejected fail-closed (H3)"
)

# AX-17 / AX-18: typed class fields are the decision-bearing datum.
axes["AX-17"]["delta_rule"] += (
    " v2: the declared/verified class on each side MUST be recorded in the typed complexity_class_a/complexity_class_b fields of the AxisVerdict; a within-rank class comparison decided only in prose justification is invalid and voids the record."
)
axes["AX-18"]["delta_rule"] += (
    " v2: the declared/verified scaling class on each side MUST be recorded in the typed complexity_class_a/complexity_class_b fields of the AxisVerdict; a within-rank class comparison decided only in prose justification is invalid and voids the record."
)

v2["axis_lattices"] = v1["axis_lattices"]

# ---- verdict_schema v2 ----
v2["verdict_schema"] = (
    "TournamentVerdict := an ordered set of exactly 22 AxisVerdict records, one per axis, and NOTHING else — the schema deliberately contains NO aggregate, total, score, weight, count-of-wins, or overall-winner field, so compensation across axes is structurally impossible (there is no place to write it). "
    "AxisVerdict := { axis_id: enum{AX-01..AX-22} (required, unique across the record set); "
    "rank_a: one of — a rung from the axis's frozen rank_levels; the literal UNKNOWN; or the typed object KNOWN_UPPER_BOUND{cap: rung}, meaning the true rank is UNKNOWN but provably <= cap per order_definition (required; never null, never a value outside this domain); rank_b: same domain (required); "
    "complexity_class_a, complexity_class_b: typed class identifiers from the separately frozen benchmark-class vocabulary — REQUIRED for AX-17 and AX-18, where they carry the declared/verified complexity or scaling class that any within-rank comparison uses, and REQUIRED-null for every other axis; the decision-bearing class NEVER lives only in prose (v2, closing the untyped-decision-datum defect); "
    "stability_certificate: optional content-addressed reference to a machine-checked invariance proof per unknown_rule(4) — when present it licenses a KNOWN winner value even though a rank field is UNKNOWN, because the certificate shows the verdict identical under ALL completions of the UNKNOWN; "
    "winner: enum{A, B, TIE, UNKNOWN, INCOMPARABLE} — in v2 winner is a DERIVED CHECK BIT, not an independent datum: any reader MUST be able to recompute it from the typed fields (rank_a, rank_b, caps, complexity_class_a/b, stability_certificate) plus the axis's frozen delta_rule, and a record whose stored winner disagrees with that recomputation is INVALID and voids the entire verdict set fail-closed (H3, H8). Derivation of winner: TIE only when rank_a and rank_b are both KNOWN rungs and equal (a cap never grounds TIE); A (resp. B) only when the sides are comparable per order_definition — KNOWN vs KNOWN, or KNOWN vs capped opponent — and the gap satisfies the axis delta_rule; for AX-17/18 the within-equal-rank class clause is decided ONLY from the typed complexity_class fields, and within equal ranks >= R3 with classes equal or class-incomparable the record is TIE with both classes recorded — this is the v2 RESCOPE of v1's 'TIE-with-noted-gap' clause, whose general form was dead (every delta_rule fires at >= 1 full rank, so a KNOWN unequal-rank sub-delta gap cannot exist) and self-contradictory (it forced TIE with unequal rank fields), and which is therefore DELETED everywhere outside this AX-17/18 class case; UNKNOWN whenever either rank is UNKNOWN (or capped without a cap-decidable comparison) and no stability_certificate applies, per unknown_rule; INCOMPARABLE only for the evidence-type conflict case defined in incomparable_rule; "
    "justification: string (required; must state, for each assigned rank or cap, which frozen ladder criterion the evidence satisfies — for a cap, which reproducible counterexample or declared-mechanism-class argument bounds it — and, for a win, which delta_rule clause the gap meets; restating conclusions without ladder reference is invalid; prose here is explanatory only and never decision-bearing); "
    "evidence_refs: non-empty array of content-addressed references to frozen evidence artifacts (required even for UNKNOWN, where it references the attempted-and-failed verification record), each carrying a typed evidence_status from enum{VERIFIED_FROM_SOURCE, VERIFIED_FROM_SECONDARY, UNKNOWN_SOURCE_UNREACHABLE}: VERIFIED_FROM_SOURCE requires third-party-recomputable verification against the primary artifact itself (H8); VERIFIED_FROM_SECONDARY (v2) marks search-excerpt, relayed, or vendor-declared material and NEVER grounds a rank — at most a KNOWN_UPPER_BOUND cap via a declared-mechanism-class argument; a reference to a producer's self-declaration is never admissible as rank evidence (H8) }. "
    "Global dominance is never stored: it is recomputed by any reader as the pure conjunction over the 22 records per order_definition, FROM THE TYPED FIELDS ONLY (ranks, caps, complexity classes, stability certificates) — never from winner bits and never from prose — as all-axes >= with at least one delta-satisfying strict gap and zero UNKNOWN-effective and zero INCOMPARABLE records, where a record is UNKNOWN-effective unless decided by KNOWN ranks, a valid cap comparison, or a stability certificate. "
    "A verdict set with any UNKNOWN-effective or INCOMPARABLE record cannot ground elimination of the disadvantaged candidate (H2, H3) — with the two v2 exceptions that carry full eliminative force because they are proofs, not presumptions: cap-derived strict dominance over a closed/external candidate, and stability-certified strict dominance per unknown_rule; otherwise the set grounds the obligations in unknown_rule / incomparable_rule instead."
)

# ---- termination_rule v2 ----
v2["termination_rule"] = (
    "The tournament terminates SUCCESSFULLY only when BOTH conditions hold simultaneously: "
    "(T1) two consecutive FULL rounds — each round being a complete pass in which every active challenger-generation mechanism (adversarial designers, counter-design agents, synthesis obligations from incomparable_rule, and reopened-UNKNOWN resolutions) runs to completion against the current front — end with ZERO surviving challengers: every generated challenger was either strictly dominated per order_definition with a complete 22-axis verdict set containing no UNKNOWN-effective and no INCOMPARABLE record (cap-derived and stability-certified records count as decided, per verdict_schema), or was merged via a discharged synthesis obligation; "
    "AND (T2, v2 — registry-relative) an independent completeness critic (fresh context, no access to the front's design rationale, per the internal-adversary protocol) certifies, with its search procedure itself recorded and replayable (H5), completeness RELATIVE TO THE COMMITTED, HASH-FROZEN GENERATION-CLASS REGISTRY: every generation class in the registry over the 22 axes and H1-H8 has been instantiated and adjudicated, and the registry's content hash is embedded in the termination record. The critic additionally attempts to construct challenger classes OUTSIDE the registry; a failed construction attempt is recorded as CORROBORATION ONLY — beyond the registry the completeness question is typed UNKNOWN, and no procedure may certify the open-class negative 'zero unexplored classes remain' in the absolute (failure-to-find is never a pass, H2 — the same committed-finite-class discipline the AX-10 regime applies to mutation classes). Accordingly the STRONGEST success state this instrument can issue is SUPREME-RELATIVE-TO-REGISTRY(registry-hash); an unqualified supremacy declaration is not derivable from it, and any successor registry version reopens termination. "
    "Registry integrity: a generation class may be removed from the registry ONLY by a full 22-axis adjudication of a representative — or, for closed/external candidates, by cap-derived strict dominance per order_definition; a prose-only dominance conjecture never removes a class, which remains a surviving challenger under T1 until adjudicated. "
    "Cap and stability interplay with T1: an UNKNOWN axis on a closed/external candidate does not persist as a surviving challenger once that candidate is strictly dominated via cap-derived verdicts — its resolution obligation is discharged by the recorded cap adjudication; an UNKNOWN axis on a front member still blocks as before, except where a stability certificate provably decides every pairwise conclusion depending on it, in which case the residual obligation is the certificate's own re-verification, not an open verdict. "
    "No effort limit of any kind — round count, wall-clock time, token/compute budget, agent count, or organizer decision — may substitute for T1+T2 or authorize declaring a winner: limits bound effort, never confer success. If any budget or externally imposed limit is exhausted before T1 and T2 both hold, the mandatory outcome is TOURNAMENT_INCOMPLETE — a typed, fail-closed terminal state (H3) that records the surviving front, all open UNKNOWNs, all undischarged synthesis obligations, the registry hash, and the last completeness-critic report, and that expressly does NOT crown any candidate supreme. "
    "Any open UNKNOWN axis on a front member (not discharged by cap adjudication or a stability certificate), or any undischarged INCOMPARABLE synthesis obligation, is itself a surviving challenger for T1 purposes: the tournament cannot terminate successfully around it. Termination status is a derived, recomputable fact from the round records and the registry hash (H8), never a declaration."
)

# ---- unknown_rule v2 ----
v2["unknown_rule"] = (
    "UNKNOWN is a first-class typed rank value (H2), assigned on an axis whenever no independently re-checkable evidence (H8) establishes any frozen rank for a candidate — including when evidence exists but is producer-declared or secondary-relayed only (evidence status VERIFIED_FROM_SECONDARY), partial over the axis's required coverage, or non-recomputable. v2 adds the bounded form: an UNKNOWN rank may carry a KNOWN_UPPER_BOUND cap established per order_definition (reproducible behavioral counterexample, or declared-mechanism-class argument); the cap bounds the unknown from above without resolving it. Effects, all fail-closed (H3): "
    "(1) UNKNOWN blocks comparison — an AxisVerdict with either rank UNKNOWN has winner=UNKNOWN, and no pairwise >=_T, >_T, TIE, or equality conclusion may issue for the pair while any of its 22 records is UNKNOWN-effective — with exactly two v2 exceptions, both proofs rather than presumptions: (a) a record decided by a valid cap comparison per order_definition (KNOWN rank vs opponent's cap), and (b) a conclusion accompanied by a machine-checked stability certificate proving it identical under ALL completions of every UNKNOWN input it ranges over. In both exceptions the underlying rank remains UNKNOWN — only the derived conclusion is KNOWN, and it is typed KNOWN-via-cap or KNOWN-with-stability-certificate, never bare KNOWN. "
    "(2) UNKNOWN never upgrades — it is never treated as equality, as a pass, as 'presumed at least rank R1', or as resolved by time, repetition, majority of assessors, or organizer decision; a cap is not an upgrade (the rank stays UNKNOWN), and VERIFIED_FROM_SECONDARY material never establishes a rank; the ONLY exit from UNKNOWN is new frozen, recomputable evidence establishing a definite rank, adjudicated in a subsequent round. "
    "(3) UNKNOWN blocks elimination and success both ways — a candidate is never eliminated on the strength of an opponent's UNKNOWN axis, and never advanced past one of its own — again with the two v2 proof-carrying exceptions: (a) strict dominance derived from KNOWN ranks against the opponent's caps eliminates the capped candidate (sound: true rank <= cap by construction); (b) a stability-certified strict-dominance verdict eliminates despite the UNKNOWN inputs it is provably invariant over. Every remaining UNKNOWN spawns a typed resolution obligation (what evidence would decide the rank, and by which ladder criterion) that counts as a surviving challenger under termination_rule T1, except as discharged by cap adjudication per termination_rule. "
    "(4) UNKNOWN propagates — any derived fact computed over an UNKNOWN input (including the global dominance conjunction) is itself UNKNOWN, never defaulted — EXCEPT (v2, certified-invariance carve-out) a derived fact carrying a certified invariance (stability) proof: a machine-checked, offline re-checkable certificate that quantifies over ALL completions of the UNKNOWN input(s) and shows the derived value identical under every completion (trivially: A OR TRUE = TRUE for unknown A; non-trivially: exhaustive case-split, three-valued Kleene evaluation, exact stability computation). Such a derived fact is KNOWN-with-stability-certificate; the input itself remains UNKNOWN; this is quantification over completions, not guessing, so H2 is intact and H5 holds (the certificate is a pure deterministic derivation from frozen inputs); absence of such a certificate leaves the derived fact UNKNOWN, fail-closed. "
    "(5) UNKNOWN is evidenced — the verdict's evidence_refs must reference the attempted verification and its failure mode, so third parties can recompute that UNKNOWN was the correct assignment (H8); a cap's evidence_refs must make the behavioral counterexample re-runnable or the declared-mechanism-class argument re-derivable; a stability certificate is itself a frozen artifact whose quantification over completions is third-party re-checkable (H8)."
)

# ---- incomparable_rule v2 (S1/S2 text preserved; S2 exercise recorded) ----
v2["incomparable_rule"] = v1["incomparable_rule"] + (
    " V2 REFINEMENT RECORD (S2 exercised, version-stamped instrument_version 2.0.0, pre-registered before any v2 verdict issues): this version applies the S2 lattice-refinement procedure to four rungs and to the AxisVerdict record — AX-01 R5 (raised to certified unique-status semantics strictly above grounded), AX-07 R3/delta and AX-12 R3 (restated as single-canonical-serialization-point guarantees: physical single writer OR consensus-established logical writer with machine-checked nonforking, admission BEFORE canonicalization), AX-10 R4 (restated in design-neutral guarantee terms), and the verdict schema itself (typed complexity_class_a/b fields, winner as derived check bit, deletion of the dead TIE-with-noted-gap clause, KNOWN_UPPER_BOUND rank type, VERIFIED_FROM_SECONDARY evidence status, stability_certificate field). Per this rule, ALL prior verdicts on AX-01, AX-07, AX-10, and AX-12 — and any verdict relying on the deleted clause or on untyped class prose — are invalidated and must be re-adjudicated under v2 before further use."
)

# ---- changelog ----
v2["changelog"] = [
    {"finding": "ceiling-falsifier P0-1 + closure-attacker P0-3 (AX-01 false uniqueness lemma; ideal/eager/sceptical-preferred are unique, deterministic, decidable)", "change": "ADOPTED THE STRONGER FORM per the supreme law (option (b), not the convenient relabel): AX-01 R5 raised to 'certified-unique-status-defeater-closed' — certified unique-status semantics STRICTLY above grounded (ideal/eager, or sceptical-preferred with certified exhaustive-extension search); polynomial time explicitly declared a non-criterion governed by AX-17; grounded-only proof-carrying systems score R4 with a recorded semantics gap. S2 refinement recorded; all prior AX-01 verdicts invalidated."},
    {"finding": "ceiling-falsifier P0-3 (unconditional UNKNOWN propagation below the attainable maximum; freeze inconsistent with closure DIM-12 exact-stability family)", "change": "Certified-invariance (stability) carve-out added: unknown_rule(4) now permits KNOWN-with-stability-certificate derived facts provably invariant over ALL completions of the UNKNOWN; carve-out threaded consistently through unknown_rule(1) and (3), order_definition, verdict_schema (new stability_certificate field), and termination_rule T1; AX-09 delta_rule records that a stability-certified verdict is compatible with H2 (quantification, not guessing). Absence of certificate: UNKNOWN stands, fail-closed."},
    {"finding": "closure-attacker P0-1 (K-COM structurally unadjudicable under H8 + unknown_rule; T1 unreachable; assessor rank claims inadmissible)", "change": "New rank type KNOWN_UPPER_BOUND{cap} added to order_definition and verdict_schema: caps established only by reproducible behavioral counterexamples or declared-mechanism-class arguments; dominance A >_T X derivable from rank_k(A) >= cap_k(X) with a delta-satisfying gap on >= 1 axis; caps never ground the capped candidate's advancement, TIE, or win. termination_rule: cap-dominated closed/external candidates' UNKNOWN axes no longer persist as eternal T1 challengers — their resolution obligations discharge via the recorded cap adjudication."},
    {"finding": "instrument-and-honesty P1-1 (VERIFIED_FROM_SOURCE assigned to search-excerpt/vendor-relayed material; leak into rank claims)", "change": "Typed evidence_status enum {VERIFIED_FROM_SOURCE, VERIFIED_FROM_SECONDARY, UNKNOWN_SOURCE_UNREACHABLE} added to every evidence_ref in verdict_schema; VERIFIED_FROM_SECONDARY (search-excerpt/vendor-declared) NEVER grounds a rank — at most a KNOWN_UPPER_BOUND cap via a declared-mechanism-class argument; restated in order_definition and unknown_rule(2)."},
    {"finding": "instrument-and-honesty P1-2 (dead self-contradictory TIE-with-noted-gap clause; winner/rank redundancy with no precedence; AX-17/18 class decided in untyped prose)", "change": "Verdict schema: the general TIE-with-noted-gap clause DELETED (provably unreachable: every delta_rule fires at >= 1 full rank) and RESCOPED to the sole live case — within-equal-rank class comparison on AX-17/18, decided ONLY from new typed complexity_class_a/complexity_class_b fields (required for AX-17/18, required-null elsewhere); winner redefined as a DERIVED CHECK BIT recomputable from typed fields, mismatch invalidates the whole verdict set fail-closed; global dominance recomputes from typed fields only, never from winner bits or prose. AX-17/AX-18 delta_rules amended to require the typed fields."},
    {"finding": "instrument-and-honesty P1-3 (T2 certifies an uncertifiable open-class negative — UNKNOWN treated as the pass permitting SUCCESS)", "change": "T2 restated registry-relative: completeness certified ONLY relative to the committed, hash-frozen generation-class registry (hash embedded in the termination record); the critic's failed construction attempt outside the registry is CORROBORATION only, typed UNKNOWN beyond the registry; strongest success state renamed SUPREME-RELATIVE-TO-REGISTRY(hash); unqualified supremacy declared underivable; successor registry versions reopen termination."},
    {"finding": "instrument-and-honesty P1-5(a) (AX-10 R4 paraphrases LAWMAX process vocabulary — lattice tailoring)", "change": "AX-10 R4 restated in design-neutral guarantee terms: structurally independent adversarial review (fresh context, no implementer rationale) as blocking admission gate; every finding reaches a recorded, append-only-auditable terminal disposition (fixed at origin / refuted with recorded proof / tracked to scheduled removal)."},
    {"finding": "instrument-and-honesty P1-5(b) + closure-attacker P1-7 (AX-07/AX-12 R3 encode B0's single-writer mechanism; H4 applied asymmetrically between K-BFT and CRDTs)", "change": "AX-07 R3 and AX-12 R3 de-tailored to the guarantee: 'single canonical serialization point (physical single writer OR consensus-established logical writer with machine-checked nonforking)'; AX-07 delta_rule updated accordingly; H4's operative content frozen design-neutrally in both rungs as admission-BEFORE-canonicalization at one serialization point — under which consensus-commit admission qualifies and merge-after-acceptance replication does not, turning the closure's K-BFT/CRDT distinction from gloss into derivable proof. S2 refinement recorded; prior AX-07/AX-12 verdicts invalidated."},
    {"finding": "instrument-and-honesty P0-1 (independence claim false: ceilings/K-SUP tailored to B0 while freeze claims 'no reference to any existing design')", "change": "order_definition restated honestly: the FROZEN instrument holds only design-neutral guarantee statements; all attainment witnesses (including B0 file references) live in a separate NON-FROZEN attainment-witness appendix with no normative force and no role in rank assignment; the two tailored rungs are named and fixed in this version; appendix bias acknowledged, not denied. (The ceiling-by-ceiling split into guarantee statement + attainment-witness appendix, and the K-SUP redefinition over guarantee profiles, close at the ceilings/closure seats; this is the freeze-side half.)"},
    {"finding": "instrument-and-honesty P1-4 (rank-grade prose — 'at ceiling grade', 'supreme-grade', 'attained' — stated as established inside derivations)", "change": "order_definition now forbids rank-grade language in any frozen derivation: such statements are typed hypotheses confined to the non-frozen attainment appendix, UNKNOWN until independently replayed. (Rewriting the specific ceiling sentences closes at the ceilings seat.)"},
    {"finding": "instrument-and-honesty P0-2 (>=12 families eliminated by prose lemma with no retained representative — pruning before adjudication)", "change": "Freeze-side closure: termination_rule registry-integrity clause added — a generation class leaves the hash-frozen registry ONLY via a full 22-axis adjudication of a representative (or cap-derived strict dominance for closed candidates); prose-only dominance conjectures never remove a class, which persists as a T1 surviving challenger. (Naming representatives / reclassifying lemmas as conjectured dominance closes at the closure seat.)"},
    {"finding": "ceiling-falsifier P1-1 (AX-03 single-authority arbitration clause) — freeze-side scope", "change": "No AX-03 ladder change required: its rungs were already stated in guarantee terms (declared arbiter, verified protocol, certified coordination) without a single-OS-writer commitment; the serialization-point guarantee wording adopted for AX-07/AX-12 supplies the design-neutral reading the AX-03 ceiling restatement (ceilings seat) relies on."},
    {"finding": "ceiling-falsifier P0-2, P1-2..P1-8, P2-1..P2-5; closure-attacker P0-2, P1-4..P1-8, P2-9..P2-14; instrument-and-honesty P2-1..P2-6 (ceiling kinds, ABSOLUTE/RESOURCE_BOUNDED relabels, B0 placement, missing families/dimensions)", "change": "OUT OF THIS COMPONENT'S SEAT: these findings target the ceilings document and the closure/taxonomy, and close at those seats in their own v2 reconciliations (including the universal RESOURCE_BOUNDED carve-out that ABSOLUTE labels may not lean on toolchain availability/cost). The freeze v2 provides every instrument-level hook they require: KNOWN_UPPER_BOUND, VERIFIED_FROM_SECONDARY, stability certificates, typed class fields, registry-relative T2, and the de-tailored design-neutral ladders. No finding against the freeze is refuted; all freeze-directed findings are adopted, several in strengthened form per the supreme law."},
]

# order: instrument_version, order_definition, axis_lattices, verdict_schema, termination_rule, unknown_rule, incomparable_rule, changelog
out = collections.OrderedDict()
for k in ["instrument_version", "order_definition", "axis_lattices", "verdict_schema", "termination_rule", "unknown_rule", "incomparable_rule", "changelog"]:
    out[k] = v2[k]

with open(f"{BASE}/_ssp_freeze_v2.json", "w") as f:
    json.dump(out, f, ensure_ascii=False, indent=None, separators=(", ", ": "))
print("written", len(json.dumps(out)))
# sanity checks
d = json.load(open(f"{BASE}/_ssp_freeze_v2.json"))
assert len(d["axis_lattices"]) == 22
assert "KNOWN_UPPER_BOUND" in d["order_definition"] and "VERIFIED_FROM_SECONDARY" in d["verdict_schema"]
assert "stability" in d["unknown_rule"] and "SUPREME-RELATIVE-TO-REGISTRY" in d["termination_rule"]
assert "unique-status" in d["axis_lattices"][0]["rank_levels"][4]
assert "single canonical serialization point" in d["axis_lattices"][6]["rank_levels"][2]
assert "single canonical serialization point" in d["axis_lattices"][11]["rank_levels"][2]
assert "implementer rationale" in d["axis_lattices"][9]["rank_levels"][3]
assert "complexity_class_a" in d["axis_lattices"][16]["delta_rule"] and "complexity_class_a" in d["axis_lattices"][17]["delta_rule"]
assert len(d["changelog"]) == 13
print("all checks pass")
