
const AXES=[{"id":"AX-01","name":"legal-reasoning correctness and defeater sensitivity","st":"cond","mech":"Extend negation-layer.lisp into a defeater-closure admission gate emitting a reproducible evidence-rank certificate (defeaters enumerated, each {defeated|undefeated|UNKNOWN}), no LLM in the trusted derivation path.","b0":"inference-gate.lisp (JTMS well-founded-defeater gate, real, runs) + deontic-gate.lisp (~91.5% heuristic); meta-ontology.lisp declares AX-01 ABSENT-by-design.","claim":"Would add defeater-closure=closed over the LLM-authored, defeater-open answer, but the negation-layer defeater gate (one defun today) and the certificate are specified-not-implemented."},
{"id":"AX-02","name":"multi-step task decomposition and plan completeness","st":"cond","mech":"Promote validate-pipeline to a total pre-execution decision that REJECTS (all reasons) any plan failing dependency-closure, acyclicity, or goal-coverage.","b0":"dependency-graph.lisp (build-dependency-graph, topological-sort, cycle-signal, real) + pipeline-dsl.lisp; type-match COMPUTED but NOT gated.","claim":"Would decide dependency-closure+acyclicity+goal-coverage before execution, but B0 computes the type-match without gating and the completeness conjunct is spec-only."},
{"id":"AX-03","name":"agent coordination, dependency control, parallelism, arbitration","st":"cond","mech":"Parallelism scheduled off the verified DAG; arbitration = total single-writer kernel K with unique-latest + monotonic-sequence; OS capability closure denies every non-writer identity.","b0":"verify-capability-closure.sh (real OS-DAC single writer, EACCES); parallel-executor.lisp swallows per-stage errors→nil.","claim":"Real OS-DAC gives one canonical writer, but unique-latest + deterministic-replay arbitration is the spec-only kernel K (T4/T5/T6 blocked); double-writer=0 is not yet by-construction."},
{"id":"AX-04","name":"source-selection & grounding independent of corpus size","st":"now","mech":"Ground by canonical-identity (ELI/eId) over an invariant-gated closed set folded into one Merkle root; each unit ships a portable inclusion proof or /as-known returns typed UNKNOWN; O(1) lookup, invariant to corpus size.","b0":"primary-anchor.lisp (dual digest) + authority-evidence-replay.lisp (re-extraction byte-equivalence) + corpus-fingerprint.lisp (unique-eId/no-gap invariant gate).","claim":"A total function over an invariant-gated set with a third-party-verifiable Merkle inclusion path beats relevance retrieval with silent miss; independent of corpus size."},
{"id":"AX-05","name":"citation & legal-authority validation mechanism","st":"now","mech":"Hermetic fail-closed re-derivation: refuse bundle-declared roots, re-derive source→spans→extraction→normalization→graph byte-equivalence, award tier only from independently verified predicates; trusted root not recoverable from the bundle.","b0":"authority-proof-bundle.lisp (Ed25519 owner-pin, delegation-valid-at-genTime, revocation) + authority-evidence-replay.lisp (626-line producer-independent re-derivation).","claim":"Re-derives the authority tier hermetically with no self-authorization vs non-reproducible vendor status; unresolved cross-cites surfaced, not silently trusted."},
{"id":"AX-06","name":"evidence provenance & transformation-lineage completeness","st":"now","mech":"Lineage = replayable cryptographically chained function: SHA-256 before/after each op enabling byte-exact replay, genealogy bound into receipt-id, deterministic PROV-O, validate-provenance a gating completeness invariant.","b0":"merkle-authority.lisp (RFC-6962 single seat) + authority-evidence-replay.lisp (recompute-and-compare lineage, leading axis) + consolidation-proof.lisp.","claim":"Recomputes lineage rather than asserting it and gates critical steps vs human-inspection trace-back."},
{"id":"AX-07","name":"matter context, institutional & reflective memory","st":"now","mech":"Append-only SHA-256 episode chain, one writer per store, memory_recorded a COMPUTED append+read-back invariant (never a stored flag), human-signed-only reflective consolidation, no LLM in the memory path.","b0":"memory.lisp (append-only SHA-256 chain, verify-episode-chain, downgrade-resistant; episodes.sexp gitignored/runtime-created).","claim":"SHA-256-chained single-writer memory with append+read-back proof beats the DECLARED workspace persistence (competitor internals unknown)."},
{"id":"AX-08","name":"temporal & legal-state consistency","st":"now","mech":"Bitemporal version-graph: in-force computed as a fold over live journal events with zero stored derived state; effectivity a closed MONOTONE no-negation AST; replay re-verifies payload+chain+semantic hash, fail-closed on contradiction.","b0":"version-graph.lisp (bitemporal valid × known-at, :suspensive/:resolutory, replay chain, ~1000+ lines) + transparency-log.lisp (RFC-6962 consistency proofs).","claim":"Fold-computed, replay-verified, fail-closed bitemporal state with no stored derived state beats a point-in-time good-law flag."},
{"id":"AX-09","name":"contradiction, uncertainty, coverage & blind-spot handling","st":"cond","mech":"Honest ignorance as measured invariants (false_uncertainty=0, silent_scope_omissions=0, unverified_satisfactions=0) plus fail-closed contradiction (typed error, journaled-retract-only) and adversarial negative-witness gates.","b0":"rdf-canonicalization.lisp (NFC fail-hard) + verify-proof-manifest.py (cannot false-green) + version-graph.lisp (typed fail-closed contradiction). Counters exist ONLY as a comment/test strings.","claim":"Fail-closed contradiction + typed UNKNOWN + no-LLM would dominate a best-effort answer, but the honesty counters are test-fixture strings, not machine-measured standing invariants."},
{"id":"AX-10","name":"self-falsification, counter-design generation & escalation","st":"now","mech":"Adversarial self-falsification as a release-gating invariant: fresh-context critic agents on two axes + redteam-audit-v2 metamorphic families and 6 counter-proposal fixtures that MUST all be Rejected; merge blocked unless every counter-design is defeated.","b0":"capture-mutation-witness.py (mutation-kill) + run-proofs.sh (un-gameable honesty gate) + legal-counterfactual.lisp + output/redteam-audit-v2/ fixtures.","claim":"Builds and must defeat the strongest counter-design pre-emit vs review-verifies-cites; a self-falsification precondition, not a review pass."},
{"id":"AX-11","name":"workflow/tool orchestration with explicit transaction semantics","st":"cond","mech":"Total-function kernel K as single commit boundary: 9 conjuncts all-or-nothing, sequence=old+1, no-rollback, unique-latest, each step committing atomically as a signed transition_certificate or changing nothing.","b0":"write-authority.lisp (emit-graph sole RDF writer) + journal.lisp (atomic rename + fsync + RATCHET-2 CAS). emit-graph :supersede has NO fsync; K is :specification-only.","claim":"Would add all-or-nothing commit + signed certificate, but '11 machine-checked invariants' are really 11 SPECIFIED conjuncts, 0 machine-checked, and no cert is emitted."},
{"id":"AX-12","name":"institutional decision authority, review & accountable transition","st":"cond","mech":"Authority = typed role-attributable capability (TUF-class offline root, threshold, revocation); every transition signed via K's certificate; human sole merge; publisher-independent proof-carrying verification.","b0":"constitutional-dispatch.lisp (:around barrier, bypass structurally impossible) + capability-registry.lisp + adoption-decision.lisp (signed ledger). evaluate FAILS OPEN on predicate error.","claim":"Would bind every transition to a role signature under an offline root, but the signing is via the unimplemented K certificate and the gate currently fails OPEN."},
{"id":"AX-13","name":"auditability, provenance-complete replay & reproducibility","st":"now","mech":"Producer-independent full-derivation replay: refuse declared roots, re-derive source bytes→spans→…→root with recompute-and-compare at every step; portable per-provision Merkle inclusion proof + PROV-O; third party verifies offline.","b0":"authority-evidence-replay.lisp (recompute-and-compare) + release-spine.lisp (independent re-verification) + gates-runner.lisp.","claim":"Offline recompute-and-compare of the authority root beats an internal check that the reader must trust."},
{"id":"AX-14","name":"determinism under frozen inputs & nondeterminism control","st":"bench","mech":"Pure clock-/RNG-/IO-free kernel + one deterministic-time seat (SOURCE_DATE_EPOCH) + enumerated declared-nondeterminism closure; determinism/run1 vs run2 hold the deterministic partition to bit-for-bit reproduction.","b0":"config.lisp (effective-deterministic-timestamp) + rdf-canonicalization.lisp (canonical ordering). omega timestamp defaults to WALL-CLOCK unless frozen.","claim":"A deterministic no-LLM partition beats sampling-nondeterministic LLM steps, but 'reproduction error = 0 bits' is unmeasured (T6 replay blocked-toolchain)."},
{"id":"AX-15","name":"durability, crash consistency & bounded recovery","st":"now","mech":"Integrity ratchet in one journal seat: WRITE-FILE-ATOMIC (tmp+rename) + fsync of data AND parent dir; fail-closed Persistence Receipt (fsync fault → SYNC-FAILURE, never :durable); RATCHET-2 compare-and-append makes forks impossible.","b0":"journal.lisp (atomic rename(2) + fsync, RATCHET-1 honest durability with fault injection, RATCHET-2 CAS + flock). Sharpest hole: emit-graph :supersede & deploy.lisp have NO fsync.","claim":"The journal's atomic rename + double fsync + fail-closed receipt + bounded recovery beats DECLARED persistence-as-feature, for the governance/journal path."},
{"id":"AX-16","name":"progress & liveness under the declared operating model","st":"cond","mech":"Total LLM-free trusted decision: K returns Reject|Accept for every input (no exception/undefined/hang); T2 completeness, T3 sequence-advances, T7 Reject→no-state-change pin progress; single-writer CAS yields bounded retry, not deadlock.","b0":"autonomy.lisp (bounded-error resume, max-consecutive-errors) + run-proofs.sh (deterministic fail-closed exit codes). executor retry NOT idempotency-checked.","claim":"A total, bounded-step, terminating decision would beat an inspectable-but-not-provably-halting agent, but K's totality and T2/T3/T7 are undischarged."},
{"id":"AX-17","name":"latency across frozen workload distributions","st":"bench","mech":"Pure deterministic SBCL over a Merkle-pinned snapshot; execution-trace span DAG hashed into a replay-certified latency envelope (same frozen workload → bit-identical trace + identical op count).","b0":"instrumentation.lisp (with-instrumentation timing, in-memory). Effectively ABSENT — metrics gate nothing, enforce no budget/SLA, discarded on context cleanup; thinnest axis.","claim":"A no-LLM deterministic path is more reproducible than a random-variable tail, but 'deterministic p100' is a category error (op-count ≠ wall-clock) and is unmeasured."},
{"id":"AX-18","name":"throughput, scale & resource-normalized performance","st":"bench","mech":"Throughput unit = proof-carrying artifact (provision + inclusion proof + trace) re-verifiable offline in O(log n); corpus scale governed by RFC 9162 consistency proofs under single-writer append-only ratchet.","b0":"frbr-pipeline-stage.lisp (lparallel, but HARDCODES (integer 1 120) → undefined >120 articles) + inference-gate.lisp (3000-event chain demo).","claim":"Portable O(log n) offline consistency audit beats a vendor-internal re-run audit, but that is audit-cost; the throughput/scale number itself is unmeasured."},
{"id":"AX-19","name":"introspection, explanation & inspectable causal account","st":"now","mech":"Every trusted conclusion emits a machine-checkable causal proof object (typed data-only span DAG + per-authority Merkle inclusion proof), with an honest-ignorance gate forbidding a chainless conclusion; re-verifiable offline.","b0":"provenance-gate.lisp (registry-verified traces) + deliberation.lisp (MOP visible-thought invariant) + execution-trace.lisp (span DAG). omega report-* are no-op stubs.","claim":"A re-verifiable proof object beats inspectable steps where an LLM explains an LLM."},
{"id":"AX-20","name":"evolvability with monotonic capability & invariant preservation","st":"cond","mech":"Every evolution step admitted only through K (sequence-monotonicity, no-rollback, profile-continuity); capability ratcheted by a fail-closed gate scoring candidates on frozen benchmarks against a committed per-metric floor, refusing any release below floor.","b0":"capability-gate.lisp (fail-closed read-only ratchet) + architecture-gate.lisp (ontological-closure) + capability-baseline.sexp. Baseline records RAW COUNTS, not per-metric floors.","claim":"A K + frozen-benchmark ratchet would beat mutable memory accumulation, but K admission is spec-only and the baseline holds raw tallies (8/13), not per-metric floors."},
{"id":"AX-21","name":"formal assurance & architecture→source→executable transport","st":"cond","mech":"Trusted decisions specified as a language-neutral pure model carrying 9 named theorems (incl. T9 certificate-soundness), on a 5-link refinement chain (spec → F★/Coq → extracted source → CompCert binary → reproducible-build byte-identity).","b0":"admission-model.sexp (T1-T9, :specification-only, 0/17 proved, 0/13 Level-7, all :blocked-toolchain) + verify-proof-manifest.py (format/manifest checker). Central proof-debt axis.","claim":"A pure kernel + independent checker + closed TCB (rank 2) exceeds heuristic-check-with-LLM (rank ≤1), but 'rank 2-3 / machine-checked proof object' is not earned because T9 is blocked."},
{"id":"AX-22","name":"mechanism generality across legal orders without redesign","st":"fix","mech":"Jurisdiction-neutral trusted core (FRBR/ELI/PROV-O + consistency validator + RDF canonicalizer + version-graph + K) parameterized by a thin per-order content module; guarantees claimed to transport unchanged across legal orders.","b0":"greek-law-types.lisp (Greek law-type registry) + transition-certificate.cddl (content-neutral). Domain validation is Greece-COUPLED — *constitution-articles*=120 (structure.lisp).","claim":"'Reuses one core across 6 codes, ratio 1.0' is reuse across subject matter within a single Greek order — corpus breadth — which the cell itself names as the floor; the ≥2-distinct-legal-orders threshold is UNMET."}];

const LAB={now:"NOW",cond:"COND",bench:"BENCH",fix:"FIX"};
const body=document.getElementById('mbody');
AXES.forEach((a,i)=>{
  const tr=document.createElement('tr'); tr.className='mrow'; tr.tabIndex=0; tr.setAttribute('role','button');
  tr.setAttribute('aria-expanded','false');
  tr.innerHTML=`<td><div class="axc"><span class="axid">${a.id}</span><span class="axnm">${a.name}</span></div></td>`+
    Array(3).fill(`<td><div class="cellmark ${a.st}">${LAB[a.st]}</div></td>`).join('');
  const det=document.createElement('tr'); det.className='detail hidden';
  det.innerHTML=`<td colspan="4"><div class="inner">
    <div class="dfield"><div class="dl">E★ mechanism</div><div class="dv">${a.mech}</div></div>
    <div class="dfield"><div class="dl">B0 today</div><div class="dv"><span class="path">${a.b0}</span></div></div>
    <div class="dfield"><div class="dl">Honest claim</div><div class="dv">${a.claim}</div></div>
  </div></td>`;
  const toggle=()=>{const h=det.classList.toggle('hidden');tr.setAttribute('aria-expanded',String(!h));};
  tr.addEventListener('click',toggle);
  tr.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}});
  body.appendChild(tr); body.appendChild(det);
});

const CS=[
 {id:"C1",v:[["mod","IMPLEMENT"],["mod","UNBLOCK"]],gap:"Kernel K spec-only; T1–T9 blocked",chg:"Implement K in the F★ target + unblock the F★/EverParse/Coq/Perennial/CompCert toolchain (offline mirror + license decision) to discharge T1–T9.",f:"admission-model.sexp · trusted-toolchain-manifest.sexp",d:"T1–T9; AX-01/02/03/09/11/12/16/20/21"},
 {id:"C2",v:[["add","ADD"]],gap:"No certificate emitter",chg:"Add the transition_certificate emitter (verified-extracted; not a second CL seat).",f:"transition-certificate.cddl → extracted checker",d:"T9; AX-11/12/20"},
 {id:"C3",v:[["mod","MODIFY"]],gap:"emit-graph non-atomic (AX-15 hole)",chg:"Atomic temp + fsync(data) + fsync(parent dir) + rename; fail-closed Persistence Receipt.",f:"write-authority.lisp (emit-graph) · deploy.lisp",d:"AX-15 system-wide"},
 {id:"C4",v:[["mod","REPLACE"]],gap:"Hardcoded 120-article cap",chg:"Replace (integer 1 120) with a config-driven corpus bound.",f:"frbr-pipeline-stage.lisp:348,504",d:"AX-18 defined-behaviour; AX-22"},
 {id:"C5",v:[["mod","MODIFY"]],gap:"Wall-clock nondeterminism",chg:"Single frozen-clock seat (SOURCE_DATE_EPOCH); collapse duplicate time reads.",f:"omega timestamp path · circuit-breaker.lisp · config.lisp",d:"AX-14 (enables T6 run)"},
 {id:"C6",v:[["mod","REFACTOR"]],gap:"Intra-tier nondeterminism + error-swallow",chg:"Deterministic intra-tier order + transactional rollback (no continue-on-fail).",f:"parallel-executor.lisp",d:"AX-03/14/16"},
 {id:"C7",v:[["add","ENABLE"]],gap:"External quorum disabled",chg:"Enable external witness quorum (C2SP/Ed25519 cosigning); flip status, set split-view claim.",f:"witness-policy.sexp",d:"AX-03/08 distributed scope"},
 {id:"C8",v:[["mod","REPLACE"]],gap:"Runtime asserts, not proofs",chg:"Replace asserts/comment-counters with standing machine-checked invariants (false_uncertainty / silent_scope_omissions / unverified_satisfactions) + adversarial witness.",f:"version-graph.lisp · honesty-counter seat",d:"AX-09"},
 {id:"C9",v:[["mod","IMPLEMENT"]],gap:"AX-19 no-op reporting",chg:"Implement the introspection emitters; effect-typed lineage so an untraced trusted act cannot compile.",f:"omega report-stage-progress / report-unified-statistics",d:"AX-19"},
 {id:"C10",v:[["mod","MODIFY"],["rem","REMOVE"]],gap:"Constitutional gate fails open",chg:"Make evaluate fail-closed on predicate error; remove value-fabricating use-default* restarts (skip/abort only).",f:"constitutional-dispatch.lisp · frbr-conditions.lisp",d:"AX-10/12"},
 {id:"C11",v:[["mod","REFACTOR"]],gap:"Defeater gate absent",chg:"Refactor negation-layer.lisp (one OWL-disjointness defun) into the defeater-closure admission gate emitting {defeated|undefeated|UNKNOWN}.",f:"negation-layer.lisp",d:"AX-01"},
 {id:"C12",v:[["mod","MODIFY"]],gap:"Consolidation aggregate-only",chg:"Ledger from aggregate hash + step-count to a per-step before/after hash chain.",f:"consolidation-proof.lisp",d:"AX-06"},
 {id:"C13",v:[["mod","REPLACE"]],gap:"Capability baseline raw counts",chg:"Replace raw tallies (E2E-OK 8/13) with per-metric floor thresholds + negative-witness Reject/Accept pair; wire K-admission ratchet.",f:"capability-baseline.sexp · capability-gate.lisp",d:"AX-20"},
 {id:"C14",v:[["add","ADD"]],gap:"Untrusted generator absent",chg:"Add the LLM/agent candidate-producer layer in the untrusted candidates/ zone (verified out before trust).",f:"candidates/ producers",d:"superset ⊋"},
 {id:"C15",v:[["mod","MOVE"]],gap:"AX-22 Greece-coupled",chg:"Move hardcoded 120/FEK//exp/ell/revision-calendar out of domain validation into legal-order profiles as data; run ≥2 structurally distinct orders.",f:"structure.lisp · historical.lisp · greek-law-types.lisp",d:"AX-22"}
];
const cs=document.getElementById('cs');
CS.forEach(c=>{
  const row=document.createElement('div'); row.className='csrow';
  row.innerHTML=`<div class="cid">${c.id}</div><div>
    <div>${c.v.map(x=>`<span class="verb ${x[0]}">${x[1]}</span>`).join('')}</div>
    <div class="gap">${c.gap}</div>
    <div class="chg">${c.chg}</div>
    <div class="meta"><span class="files">${c.f}</span><span class="disc"><b>discharges</b> ${c.d}</span></div>
  </div>`;
  cs.appendChild(row);
});

// theme toggle (3-state aware, persisted)
(function(){
  const root=document.documentElement, btn=document.getElementById('tgl');
  let saved=null; try{saved=localStorage.getItem('estar-theme');}catch(e){}
  if(saved==='dark'||saved==='light') root.setAttribute('data-theme',saved);
  function cur(){const a=root.getAttribute('data-theme'); if(a)return a;
    return (window.matchMedia&&window.matchMedia('(prefers-color-scheme:dark)').matches)?'dark':'light';}
  btn.addEventListener('click',()=>{const n=cur()==='dark'?'light':'dark';
    root.setAttribute('data-theme',n); try{localStorage.setItem('estar-theme',n);}catch(e){}});
})();
