
const CE=[{"id":"AX-01","k":"MR+RB","kind":"MODEL_RELATIVE (semantics-relative); grounded-only restriction: RESOURCE_BOUNDED (AX-17 cost class)","head":"Maximum achievable legal-reasoning correctness under H1-H8: provable soundness AND completeness of every emitted legal conclusion w.r.t. IDEAL / SCEPTICAL-PREFERRED CERTIFIED ACCEPTANCE over the committed formal rulebase — grounded acceptance is a STRICT SUBSET (gap: even attack cycles).","raised":"Υψώθηκε: ideal/sceptical-preferred certified acceptance (grounded = tractable-unique μόνο)"},
{"id":"AX-02","k":"MR","kind":"MODEL_RELATIVE","head":"Plan-decomposition assurance: for a plan that is a DETERMINISTIC DERIVATION FROM FROZEN INPUTS, machine-checked dependency-closure, acyclicity, goal-entailment — with finite-domain synthesis + existence certificates inside the decidable class.","raised":""},
{"id":"AX-03","k":"RB","kind":"RESOURCE_BOUNDED","head":"DETERMINISTIC PARALLELISM WITH ATOMIC TIER COMMIT AT A SINGLE LOGICAL SERIALIZATION POINT — φυσικός single writer Ή machine-checked nonforking replicated total order· Calvin-class conflict-ordered execution υπερβαίνει το commutativity bound.","raised":"Υψώθηκε: 'ένα λογικό σημείο σειριοποίησης'· FLP misuse διεγράφη"},
{"id":"AX-04","k":"ABS+RB","kind":"ABSOLUTE (negative half) / RESOURCE_BOUNDED (positive clauses)","head":"Grounding: ORIGIN AUTHENTICITY όχι ισχυρότερη από transport / corroboration / attested-channel — ένα digest δεσμεύει ΤΙ ελήφθη, ποτέ ΠΟΙΟΣ το δημοσίευσε (καμία authenticity εκ των υστέρων)· τρίτος μηχανισμός: attested-channel capture.","raised":"Προστέθηκε 3ος μηχανισμός: attested-channel capture (DECO/TLSNotary/TEE)"},
{"id":"AX-05","k":"MR","kind":"MODEL_RELATIVE","head":"Ως προς δηλωμένη decidable citation grammar: SOUND AND COMPLETE PROOF-CARRYING RESOLUTION over L(G) + authority-state at legal time· formal-proposition support-verification ΕΝΤΟΣ ταβανιού (AX-01×AX-04)· NL-vs-NL εκτός.","raised":""},
{"id":"AX-06","k":"ABS+RB","kind":"ABSOLUTE (assurance) / RESOURCE_BOUNDED (cost)","head":"Lineage assurance: η γνώση του verifier φράσσεται από ό,τι παράγεται από committed bytes υπό δηλωμένες hash υποθέσεις — recompute-and-compare ΚΑΙ transparent proof-of-recomputation ισοδύναμα μέγιστα· fail-closed ολικότητα στο release closure.","raised":"Split assurance/cost· το Ω(s) απόλυτο floor διεγράφη"},
{"id":"AX-07","k":"ABS+RB","kind":"ABSOLUTE (a,b,d) / RESOURCE_BOUNDED (fork-consistency cap — witness quorum)","head":"Μνήμη: provenance-complete capture με episode commitments (erasure-compatible: salted commitments + typed erasure certificates), πλήρης tamper-evidence με recompute, fork-consistency cap αρθής με external witness quorum (διαθέσιμος πόρος).","raised":""},
{"id":"AX-08","k":"ABS+MR+RB","kind":"ABS (a; b-internal) / MR (c) / RB (b anti-rollback — quorum)","head":"Temporal: gapless monotone history (seq'=seq+1 σε ένα serialization point), bitemporal ολικότητα valid×known-at, (t,τ) εκτός committed τεκμηρίων = typed UNKNOWN — ποτέ σιωπηλά λάθος.","raised":""},
{"id":"AX-09","k":"ABS","kind":"ABSOLUTE","head":"Certified totality σε ΤΕΣΣΕΡΙΣ κατηγορίες ετυμηγορίας: PASS / FAIL / typed-UNKNOWN (κλειστή απαρίθμηση αιτιών, μηχανικά επιβεβλημένο όριο) / KNOWN-with-stability-certificate πάνω από UNKNOWN inputs· coverage = θετικά αποδεδειγμένο census.","raised":"Προστέθηκε: KNOWN-with-stability-certificate"},
{"id":"AX-10","k":"ABS","kind":"ABSOLUTE (two-regime· completeness σχετική με committed specs/classes)","head":"Self-falsification: (1) PROOF-CARRYING ΑΠΟΚΛΕΙΣΜΟΣ ΑΠΕΙΡΩΝ ΚΛΑΣΕΩΝ όπου υπάρχει machine-checked απόδειξη — ο Rice απαγορεύει το deciding, ΟΧΙ το proof-checking· (2) 100% mutation-kill σε δεσμευμένη πεπερασμένη κλάση ως floor του αναπόδεικτου.","raised":"Υψώθηκε: proofs πάνω από mutation-kill"},
{"id":"AX-11","k":"ABS+RB","kind":"RB (fsync-scoped clause) / ABS (two-generals clause)","head":"Transactions: single-commit-point atomicity — μετά από crash σε ΟΠΟΙΟΔΗΠΟΤΕ σημείο, η κατάσταση είναι ακριβώς σ_pre ή σ_post, ποτέ υβρίδιο· η αναγωγή όλων των σωστών πρωτοκόλλων σε ένα atomic switch είναι το φέρον αποδεικτέο.","raised":""},
{"id":"AX-12","k":"ABS+RB","kind":"ABSOLUTE (admission/genesis/fail-closed/process) / RB (equivocation — quorum)","head":"Εξουσία: κάθε trusted μετάβαση από ΕΝΑ total, pure, decidable kernel predicate K — κάθε άλλη έκβαση (και σφάλμα του ίδιου του gate) = καταγεγραμμένη υπογεγραμμένη άρνηση με μηδενική αλλαγή· authority = recomputable chain από genesis anchor (οι υπογραφές μεταφέρουν εμπιστοσύνη, δεν τη δημιουργούν).","raised":""},
{"id":"AX-13","k":"ABS+RB","kind":"ABSOLUTE (assurance) / RESOURCE_BOUNDED (cost)","head":"Auditability: κάθε trusted output με certificate δεμένο στο ΠΛΗΡΕΣ closure (source bytes, code identity, pinned toolchain, config)· τρίτος, πλήρως offline, με μηδενική εμπιστοσύνη στον παραγωγό, επαληθεύει το μοναδικό derivation result· STARKs ισοδύναμα μέγιστα.","raised":"STARKs = ισοδύναμα μέγιστα (ψευδές trusted-setup διορθώθηκε)"},
{"id":"AX-14","k":"ABS","kind":"ABSOLUTE (output = f(committed closure)· per-pinned-class determinization)","head":"Determinism: κάθε trusted παραγωγή = ολική συνάρτηση του committed closure — byte-identical σε κάθε επανεκτέλεση εντός pinned class· ΚΑΙ οι untrusted producers determinizable ανά pinned class (batch-invariant kernels)· residue: cross-hardware portability μέσω record/replay.","raised":"Producers determinizable (v1 exclusion αποσύρθηκε)"},
{"id":"AX-15","k":"RB","kind":"RESOURCE_BOUNDED (declared platform)","head":"Durability στο δηλωμένο μοντέλο: durable ⇔ data+metadata+parent-dir fsynced· FAIL-CLOSED READ-BACK — μετάβαση μετρά committed μόνο μετά recompute-and-compare των persisted bytes· bounded recovery.","raised":""},
{"id":"AX-16","k":"RB","kind":"RESOURCE_BOUNDED (declared operating model)","head":"Liveness: CONDITIONAL BOUNDED PROGRESS — κάθε αίτημα τερματίζει σε αποδεκτό αποτέλεσμα ή typed bounded refusal· ποτέ hang, ποτέ σιωπηλό deadlock/livelock εντός του δηλωμένου μοντέλου.","raised":""},
{"id":"AX-17","k":"RB","kind":"RESOURCE_BOUNDED","head":"Latency: ΑΚΡΙΒΕΣ offline-verifiable deterministic cost certificate ανά workload item + fail-closed cost-budget gate· wall-clock: k-of-n external-time-authority bracketing (residue: εμπιστοσύνη στο εξωτερικό quorum, όχι στον παραγωγό).","raised":""},
{"id":"AX-18","k":"RB","kind":"RESOURCE_BOUNDED","head":"Throughput: T_p ≥ max(W/p, S, ⌈n/b⌉·c_batch) — όλα τα φράγματα παράγωγα του committed corpus config, ποτέ σταθερές· γραμμικό verification floor = λειτουργικό (toolchain-relative), αρθές από transparent succinct proofs.","raised":"Λειτουργικό floor, όχι απόλυτο"},
{"id":"AX-19","k":"MR+RB","kind":"MR (rung 1) / +RB (rung 2 — AX-21 πόροι)","head":"Introspection: ο μέγιστος causal λογαριασμός = το ίδιο το replayable derivation (bit-equality από τρίτους)· completeness-of-mediation σε δύο σκαλιά — δομικό (τώρα) και verified-perimeter (με AX-21 πόρους).","raised":""},
{"id":"AX-20","k":"ABS","kind":"ABSOLUTE (widened formula)","head":"Evolvability: ratchet-μονοτονία στην ΕΝΩΣΗ committed executable measures ΚΑΙ machine-checked preservation proofs — αδυνατότητα μόνο για ικανότητες ούτε μετρημένες ούτε proof-covered· το certified σύνολο μόνο μεγαλώνει.","raised":"Υψώθηκε: measures ∪ proofs"},
{"id":"AX-21","k":"RB","kind":"RESOURCE_BOUNDED (declared toolchain)","head":"Assurance transport: κάθε κρίκος = machine-checked proof replayable offline Ή recompute-and-compare conformance, τερματίζοντας σε απαριθμημένο, ελαχιστοποιημένο, hash-committed TCB· ΟΝΟΜΑΣΜΕΝΟ το ανώτερο: CakeML/Brack verified substrate — αποκλεισμένο μόνο από τη δηλωμένη επιλογή SBCL.","raised":"Ονομάστηκε το ανώτερο transport (supreme-law rule 3)"},
{"id":"AX-22","k":"MR","kind":"MODEL_RELATIVE","head":"Generality: profile-parametricity — κάθε trusted μηχανισμός αμετάβλητος κατά την εναλλαγή legal-order profile (καθαρά data)· + profile-composition/conflict-of-laws meta-rules ως committed meta-rulebase· UNKNOWN για μη-κωδικοποιημένο renvoi.","raised":""}];
const CL=[{"id":"K-B0-TARGET","name":"LAWMAX B0 target profile (the completed roadmap as a design)","reg":"U_T"},{"id":"K-SUP","name":"Ceiling-Envelope Synthesis (per-dimension join των guarantee profiles)","reg":"U_T"},{"id":"K-ARG","name":"Certified Defeasible-Argumentation Engine","reg":"U_T"},{"id":"K-CAT","name":"Verified Statutory Calculus","reg":"U_T"},{"id":"K-CBR","name":"Precedential-Constraint Case-Based Reasoner","reg":"U_T"},{"id":"K-NSV","name":"Propose/Verify-Out Neuro-Symbolic Pipeline","reg":"U_T"},{"id":"K-RULES","name":"Deterministic Monotonic Rule Engine (classical expert system)","reg":"U_T"},{"id":"K-TLOG","name":"Witnessed Transparency Institution","reg":"U_T"},{"id":"K-BFT","name":"Replicated Deterministic Legal Ledger","reg":"U_T"},
{"id":"K-COM","name":"Commercial Agentic Suite — CoCounsel · Protégé · Harvey (το εμπορικό δάπεδο)","reg":"D_T"},{"id":"K-COM+","name":"Partially-Verified Commercial Hybrid (το κελί καλύφθηκε πριν το καταλάβει vendor)","reg":"D_T"},{"id":"K-B0-SHIPPED","name":"LAWMAX B0 όπως είναι (αυτό το repo — H3 παραβιάσεις σε ονομασμένες έδρες)","reg":"D_T"},{"id":"K-CRDT","name":"Local-First Convergent Matter Fabric","reg":"D_T"},{"id":"K-AGT","name":"Durable-Execution Agent Platform","reg":"D_T"},{"id":"K-TEE","name":"Attested Replayable LLM Pipeline","reg":"D_T"},{"id":"K-GRAPH","name":"Probability-Isolated Deterministic Knowledge-Graph Service","reg":"D_T"},{"id":"K-HUM","name":"Expert-Human Practice Baseline","reg":"D_T"}];

const ct=document.getElementById('ct');
CE.forEach(a=>{
  const row=document.createElement('div'); row.className='crow'; row.tabIndex=0; row.setAttribute('role','button'); row.setAttribute('aria-expanded','false');
  const tags=a.k.split('+').map(t=>{
    const cls=t==='ABS'?'t-abs':(t==='MR'?'t-mr':'t-rb');
    return `<span class="tag ${cls}">${t}</span>`;
  }).join('')+(a.raised?'<span class="tag t-up">ΥΨΩΘΗΚΕ</span>':'');
  row.innerHTML=`<div class="head"><span class="axid">${a.id}</span><span class="axtx">${a.head}</span><span class="tags">${tags}</span></div>
    <div class="more">${a.raised?`<div class="raisenote">▲ ${a.raised}</div>`:''}<div class="kd">kind: ${a.kind}</div></div>`;
  const tog=()=>{const o=row.classList.toggle('open');row.setAttribute('aria-expanded',String(o));};
  row.addEventListener('click',tog);
  row.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tog();}});
  ct.appendChild(row);
});
const ut=document.getElementById('ut'), dt=document.getElementById('dt');
CL.forEach(c=>{
  const d=document.createElement('div'); d.className='krow';
  d.innerHTML=`<span class="kid">${c.id}</span><span class="knm">${c.name}</span>`;
  (c.reg==='U_T'?ut:dt).appendChild(d);
});
(function(){
  const root=document.documentElement, btn=document.getElementById('tgl');
  let saved=null; try{saved=localStorage.getItem('sspg1-theme');}catch(e){}
  if(saved==='dark'||saved==='light') root.setAttribute('data-theme',saved);
  const cur=()=>root.getAttribute('data-theme')||((window.matchMedia&&window.matchMedia('(prefers-color-scheme:dark)').matches)?'dark':'light');
  btn.addEventListener('click',()=>{const n=cur()==='dark'?'light':'dark';root.setAttribute('data-theme',n);try{localStorage.setItem('sspg1-theme',n);}catch(e){}});
})();
