;;;; systems/orchestrator-omega-modules/prov-activity.lisp
;;;; PROV-O Activity Node - Complete Provenance Chain
;;;; ΟΜΕΓΑ-LEVEL: Research-grade provenance tracking
;;;;
;;;; The PROV-O Activity represents the generation process for an article.
;;;;
;;;; Architecture:
;;;;   - One Activity per article generation
;;;;   - Activity URI: .../activity/frbr-gen/syntagma/art-N/{timestamp}
;;;;   - Links to software agent (Orchestrator)
;;;;   - Links to human agent (Spyridon Stavropoulos)
;;;;   - All entities (Article, Work, Expression, Manifestation, Formats) link via prov:wasGeneratedBy
;;;;
;;;; Compliance:
;;;;   - PROV-O v1.0 complete
;;;;   - W3C PROV-DM compliant
;;;;   - Research reproducibility standard

(in-package :orchestrator.model)

;;; ============================================================
;;; PROV-O ACTIVITY CLASS
;;; ============================================================

(defclass prov-activity (frbr-resource)
  ((article-number :accessor activity-article-number
                   :initarg :article-number
                   :type integer
                   :documentation "Article number this activity generated")

   (corpus-name :accessor activity-corpus-name
                :initarg :corpus-name
                :type string
                :initform "syntagma"
                :documentation "Corpus short name (e.g., 'syntagma')")

   (start-time :accessor activity-start-time
               :initarg :start-time
               :type string
               :documentation "ISO-8601 start timestamp")

   (end-time :accessor activity-end-time
             :initarg :end-time
             :type string
             :documentation "ISO-8601 end timestamp")

   (software-agent :accessor activity-software-agent
                   :initarg :software-agent
                   :type string
                   :initform "https://stavropouloslaw.com/software/orchestrator/v1.3"
                   :documentation "Software agent URI")

   (human-agent :accessor activity-human-agent
                :initarg :human-agent
                :type string
                :initform "https://stavropouloslaw.com/identity#spyridon-stavropoulos"
                :documentation "Human agent URI")

   (source-text-uri :accessor activity-source-text-uri
                    :initarg :source-text-uri
                    :type string
                    :documentation "URI of source text used")

   (generated-entities :accessor activity-generated-entities
                       :initarg :generated-entities
                       :type list
                       :initform nil
                       :documentation "List of entity URIs generated by this activity"))

  (:metaclass frbr-resource-class)
  (:documentation "PROV-O Activity - Represents FRBR generation process"))

;;; ============================================================
;;; CONSTRUCTOR FUNCTION
;;; ============================================================

(defun make-prov-activity (&key article-number
                                 (article-suffix "")
                                 corpus-name
                                 start-time
                                 end-time
                                 source-text-uri)
  "Create PROV-O Activity instance

   URI Pattern: .../activity/frbr-gen/{corpus}/art-{id}/{timestamp}

   Arguments:
     article-number:   Integer (η αληθινή βάση — βλ. article-base-number)
     article-suffix:   Γράμμα-επίθημα ή πλήρες label lettered άρθρου (\"Α\"/\"5Α\")
     corpus-name:      String (e.g., 'syntagma')
     start-time:       ISO-8601 timestamp string
     end-time:         ISO-8601 timestamp string
     source-text-uri:  URI of source text

   Returns:
     prov-activity instance

   P1b [0050]#2: η ταυτότητα του activity χτίζεται από τη ΜΙΑ έδρα
   (article-uri-id / pad-article-id) ώστε το lettered άρθρο (5Α) να έχει
   ΔΙΚΟ ΤΟΥ activity (art-5Α) — αλλιώς τα 5 και 5Α μοιράζονται URI
   δραστηριότητας και η συγχώνευση των γράφων τους παράγει αντιφατικό PROV."

  (check-type article-number integer)
  (unless start-time
    (error "start-time is required for provenance activity"))

  (let* ((corpus (or corpus-name
                     (ignore-errors (orchestrator.spec:config-get "corpus.short_name"))
                     "corpus"))
         (timestamp-slug (format-timestamp-slug start-time))
         (uri (format nil "https://stavropouloslaw.com/activity/frbr-gen/~A/art-~A/~A"
                      corpus
                      (article-uri-id article-number article-suffix)
                      timestamp-slug))
         (eli-id (format nil "activity-~A-art-~A-~A" corpus
                         (pad-article-id article-number article-suffix)
                         timestamp-slug))
         (start start-time)
         (end (or end-time start)))

    (make-instance 'prov-activity
                   :uri uri
                   :eli-identifier eli-id
                   :article-number (article-base-number article-number article-suffix)
                   :corpus-name corpus
                   :start-time start
                   :end-time end
                   :source-text-uri source-text-uri)))

;;; ============================================================
;;; UTILITY FUNCTIONS
;;; ============================================================

(defun format-timestamp-slug (iso8601-timestamp)
  "Convert ISO-8601 timestamp to URL-safe slug

   '2025-01-15T10:30:00Z' → '2025-01-15T10-30Z'"

  (substitute #\- #\: iso8601-timestamp))

(defun add-generated-entity (activity entity-uri)
  "Add entity URI to activity's generated-entities list"
  (push entity-uri (activity-generated-entities activity))
  activity)

;;; Note: Validation removed to avoid conflict with orchestrator.model:validate-instance function

;;; ============================================================
;;; EXPORTS
;;; ============================================================

(export '(prov-activity
          make-prov-activity
          activity-article-number
          activity-corpus-name
          activity-start-time
          activity-end-time
          activity-software-agent
          activity-human-agent
          activity-source-text-uri
          activity-generated-entities
          add-generated-entity
          format-timestamp-slug))
