;;;; deployment/LAWMAX-REPO-ONTOLOGY-MAP.sexp — ΠΑΡΑΓΟΜΕΝΟ από ζωντανά μητρώα.
;;;; Evidence ανά γραμμή: :owner-file (πηγή) ή live registry (μητρώο). ΜΗΝ επεξεργάζεσαι
;;;; με το χέρι — αναπαράγεται· κανονιστική πηγή = LAWMAX-ARCHITECTURE-CONSTITUTION.sexp.
(:lawmax-ontology-map
 :commit "85b8f7f1658d9348ede4dbd116642fcc7b9aa5dd"
 :branch "claude/ministry-justice-url-candidates-twghsj"
 :dirty-status "dirty: ?? deployment/LAWMAX-ARCHITECTURE-CONSTITUTION.sexp"
 :evidence-sources (:live-image-dump "scratchpad/raw-live.sexp μέσω sbcl runtime"
                    :command-owners "grep register-command + builtin reg table"
                    :normative "deployment/LAWMAX-ARCHITECTURE-CONSTITUTION.sexp")
 :primitives ((:id :self)(:id :law)(:id :authority)(:id :fact)(:id :proof)
              (:id :hypothesis)(:id :argument)(:id :matter)(:id :output-trust)
              (:id :evolution)(:id :institution)(:id :memory)(:id :substrate))
 :counts (:commands 150 :gates 20 :packages 135
          :capabilities 25 :contracts 39
          :components (:total 494 :files 272 :packages 135 :symbols 76))
 :commands (
  (:command "--adopt-knowledge" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--adoption-decision" :handler-file "systems/orchestrator-cli/evolution-gate.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/evolution-gate.lisp"))
  (:command "--architecture-constitution-gate" :handler-file "systems/orchestrator-cli/architecture-gate.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/architecture-gate.lisp"))
  (:command "--advisor" :handler-file "systems/orchestrator-cli/advisor.lisp" :primitive :hypothesis :evidence (:registry "*commands*" :source "systems/orchestrator-cli/advisor.lisp"))
  (:command "--advisor-gate" :handler-file "systems/orchestrator-cli/advisor.lisp" :primitive :hypothesis :evidence (:registry "*commands*" :source "systems/orchestrator-cli/advisor.lisp"))
  (:command "--affected-proofs" :handler-file "systems/orchestrator-cli/evolution-gate.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/evolution-gate.lisp"))
  (:command "--affected-traces" :handler-file "systems/orchestrator-cli/evolution-gate.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/evolution-gate.lisp"))
  (:command "--agenda" :handler-file "systems/orchestrator-cli/memory-commands.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/memory-commands.lisp"))
  (:command "--apply-upgrade" :handler-file "systems/orchestrator-cli/ingestion-commands.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/ingestion-commands.lisp"))
  (:command "--approve" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--arc-eval" :handler-file "systems/orchestrator-cli/fluid-gate.lisp" :primitive :hypothesis :evidence (:registry "*commands*" :source "systems/orchestrator-cli/fluid-gate.lisp"))
  (:command "--argue" :handler-file "systems/orchestrator-cli/subsumption-commands.lisp" :primitive :argument :evidence (:registry "*commands*" :source "systems/orchestrator-cli/subsumption-commands.lisp"))
  (:command "--ask" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--auto-update" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--autonomous" :handler-file "systems/orchestrator-cli/autonomy-missions.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/autonomy-missions.lisp"))
  (:command "--can-adopt" :handler-file "systems/orchestrator-cli/evolution-gate.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/evolution-gate.lisp"))
  (:command "--capability-contracts" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--case" :handler-file "systems/orchestrator-cli/case-workspace.lisp" :primitive :matter :evidence (:registry "*commands*" :source "systems/orchestrator-cli/case-workspace.lisp"))
  (:command "--check-upgrades" :handler-file "systems/orchestrator-cli/ingestion-commands.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/ingestion-commands.lisp"))
  (:command "--component" :handler-file "systems/orchestrator-cli/component-gate.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/component-gate.lisp"))
  (:command "--component-gate" :handler-file "systems/orchestrator-cli/component-gate.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/component-gate.lisp"))
  (:command "--component-of" :handler-file "systems/orchestrator-cli/component-gate.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/component-gate.lisp"))
  (:command "--components" :handler-file "systems/orchestrator-cli/component-gate.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/component-gate.lisp"))
  (:command "--constitution" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--contract" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--contract-gate" :handler-file "systems/orchestrator-cli/contract-gate.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/contract-gate.lisp"))
  (:command "--contracts-missing" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--deontic-gate" :handler-file "systems/orchestrator-cli/deontic-gate.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/deontic-gate.lisp"))
  (:command "--dialogue-gate" :handler-file "systems/orchestrator-cli/dialogue-gate.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/dialogue-gate.lisp"))
  (:command "--discover-fek" :handler-file "systems/orchestrator-cli/ingestion-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/ingestion-commands.lisp"))
  (:command "--draft" :handler-file "systems/orchestrator-cli/draft-commands.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/draft-commands.lisp"))
  (:command "--draft-gate" :handler-file "systems/orchestrator-cli/draft-commands.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/draft-commands.lisp"))
  (:command "--dump-pdf-text" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--emit-hypergraph" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--emit-proofs" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--emit-references" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--emit-site" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--event-gate" :handler-file "systems/orchestrator-cli/event-gate.lisp" :primitive :fact :evidence (:registry "*commands*" :source "systems/orchestrator-cli/event-gate.lisp"))
  (:command "--evolve" :handler-file "systems/orchestrator-cli/self-extension.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-extension.lisp"))
  (:command "--explain-decision" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :authority :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--extension-gate" :handler-file "systems/orchestrator-cli/self-extension.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-extension.lisp"))
  (:command "--failures" :handler-file "systems/orchestrator-cli/understanding-learning.lisp" :primitive :memory :evidence (:registry "*commands*" :source "systems/orchestrator-cli/understanding-learning.lisp"))
  (:command "--fetch-amendments" :handler-file "systems/orchestrator-cli/ingestion-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/ingestion-commands.lisp"))
  (:command "--fetch-decision" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :authority :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--fetch-pdf" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--fetch-sources" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--fetch-year" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--files-of" :handler-file "systems/orchestrator-cli/component-gate.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/component-gate.lisp"))
  (:command "--fluid-gate" :handler-file "systems/orchestrator-cli/fluid-gate.lisp" :primitive :hypothesis :evidence (:registry "*commands*" :source "systems/orchestrator-cli/fluid-gate.lisp"))
  (:command "--freeze-components" :handler-file "systems/orchestrator-cli/component-gate.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/component-gate.lisp"))
  (:command "--gap" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--gates" :handler-file "systems/orchestrator-cli/gates-runner.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/gates-runner.lisp"))
  (:command "--generation-gate" :handler-file "systems/orchestrator-cli/generation-gate.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/generation-gate.lisp"))
  (:command "--graph" :handler-file "systems/orchestrator-cli/graph-import.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/graph-import.lisp"))
  (:command "--guard-language" :handler-file "systems/orchestrator-cli/inference-gate.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/inference-gate.lisp"))
  (:command "--help" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--history" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--impact" :handler-file "systems/orchestrator-cli/graph-import.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/graph-import.lisp"))
  (:command "--index-decisions" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :authority :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--inference-gate" :handler-file "systems/orchestrator-cli/inference-gate.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/inference-gate.lisp"))
  (:command "--institution" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--intend" :handler-file "systems/orchestrator-cli/memory-commands.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/memory-commands.lisp"))
  (:command "--intentions" :handler-file "systems/orchestrator-cli/memory-commands.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/memory-commands.lisp"))
  (:command "--iq-gate" :handler-file "systems/orchestrator-cli/iq-gate.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/iq-gate.lisp"))
  (:command "--judge" :handler-file "systems/orchestrator-cli/jurisprudence-judge.lisp" :primitive :authority :evidence (:registry "*commands*" :source "systems/orchestrator-cli/jurisprudence-judge.lisp"))
  (:command "--judge-profile" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :authority :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--jurisprudence" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :authority :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--learn-understanding" :handler-file "systems/orchestrator-cli/understanding-learning.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/understanding-learning.lisp"))
  (:command "--lessons" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :memory :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--list-corpora" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--list-pipelines" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--materialize-decisions" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :authority :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--materialize-pdf" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--memory" :handler-file "systems/orchestrator-cli/memory-commands.lisp" :primitive :memory :evidence (:registry "*commands*" :source "systems/orchestrator-cli/memory-commands.lisp"))
  (:command "--memory-gate" :handler-file "systems/orchestrator-cli/memory-commands.lisp" :primitive :memory :evidence (:registry "*commands*" :source "systems/orchestrator-cli/memory-commands.lisp"))
  (:command "--mirror" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--mirror-gate" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--policies" :handler-file "systems/orchestrator-cli/approval-policy.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/approval-policy.lisp"))
  (:command "--policy" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--policy-approve" :handler-file "systems/orchestrator-cli/approval-policy.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/approval-policy.lisp"))
  (:command "--policy-gate" :handler-file "systems/orchestrator-cli/approval-policy.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/approval-policy.lisp"))
  (:command "--policy-revoke" :handler-file "systems/orchestrator-cli/approval-policy.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/approval-policy.lisp"))
  (:command "--process-pdf" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--provenance-gate" :handler-file "systems/orchestrator-cli/provenance-gate.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/provenance-gate.lisp"))
  (:command "--providers" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--read-provision" :handler-file "systems/orchestrator-cli/self-extension.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-extension.lisp"))
  (:command "--reason" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--reason-decision" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :authority :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--recall" :handler-file "systems/orchestrator-cli/memory-commands.lisp" :primitive :memory :evidence (:registry "*commands*" :source "systems/orchestrator-cli/memory-commands.lisp"))
  (:command "--reflect" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--reject" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--review" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--review-approve" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--review-reject" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--rollback-plan" :handler-file "systems/orchestrator-cli/evolution-gate.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/evolution-gate.lisp"))
  (:command "--run-all-pipelines" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--run-ingestion" :handler-file "systems/orchestrator-cli/ingestion-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/ingestion-commands.lisp"))
  (:command "--run-pipeline" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--run-tests" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--self-evolution-gate" :handler-file "systems/orchestrator-cli/evolution-gate.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/evolution-gate.lisp"))
  (:command "--self-extend" :handler-file "systems/orchestrator-cli/self-extension.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-extension.lisp"))
  (:command "--serve" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--serve-mcp" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--serve-review" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--shadow-knowledge" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--strategy" :handler-file "systems/orchestrator-cli/subsumption-commands.lisp" :primitive :argument :evidence (:registry "*commands*" :source "systems/orchestrator-cli/subsumption-commands.lisp"))
  (:command "--study-code" :handler-file "systems/orchestrator-cli/self-extension.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-extension.lisp"))
  (:command "--subsume" :handler-file "systems/orchestrator-cli/subsumption-commands.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/subsumption-commands.lisp"))
  (:command "--subsume-text" :handler-file "systems/orchestrator-cli/subsumption-commands.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/subsumption-commands.lisp"))
  (:command "--subsumption-gate" :handler-file "systems/orchestrator-cli/subsumption-commands.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/subsumption-commands.lisp"))
  (:command "--symbols-of" :handler-file "systems/orchestrator-cli/component-gate.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/component-gate.lisp"))
  (:command "--tests" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--think" :handler-file "systems/orchestrator-cli/subsumption-commands.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/subsumption-commands.lisp"))
  (:command "--thoughts" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--trace" :handler-file "systems/orchestrator-cli/provenance-gate.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/provenance-gate.lisp"))
  (:command "--trace-capability" :handler-file "systems/orchestrator-cli/provenance-gate.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/provenance-gate.lisp"))
  (:command "--trace-command" :handler-file "systems/orchestrator-cli/provenance-gate.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/provenance-gate.lisp"))
  (:command "--trace-component" :handler-file "systems/orchestrator-cli/provenance-gate.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/provenance-gate.lisp"))
  (:command "--trace-last" :handler-file "systems/orchestrator-cli/provenance-gate.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/provenance-gate.lisp"))
  (:command "--trace-last-conclusion" :handler-file "systems/orchestrator-cli/provenance-gate.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/provenance-gate.lisp"))
  (:command "--trace-legal-state" :handler-file "systems/orchestrator-cli/provenance-gate.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/provenance-gate.lisp"))
  (:command "--trace-proof" :handler-file "systems/orchestrator-cli/provenance-gate.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/provenance-gate.lisp"))
  (:command "--training-proposal" :handler-file "systems/orchestrator-cli/evolution-gate.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/evolution-gate.lisp"))
  (:command "--understanding" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--understanding-gate" :handler-file "systems/orchestrator-cli/understanding-learning.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/understanding-learning.lisp"))
  (:command "--verify-all" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--verify-all-intelligence" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--verify-consolidation" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--verify-corpus" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--verify-intelligence" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--verify-proof" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--version" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "--watch-decisions" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :authority :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--watch-fek" :handler-file "systems/orchestrator-cli/ingestion-commands.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/ingestion-commands.lisp"))
  (:command "--what-if" :handler-file "systems/orchestrator-cli/evolution-gate.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/evolution-gate.lisp"))
  (:command "--why" :handler-file "systems/orchestrator-cli/graph-import.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/graph-import.lisp"))
  (:command "--ίδρυμα" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--αναστοχασμός" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--αυτόνομα" :handler-file "systems/orchestrator-cli/autonomy-missions.lisp" :primitive :institution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/autonomy-missions.lisp"))
  (:command "--γράφος" :handler-file "systems/orchestrator-cli/graph-import.lisp" :primitive :law :evidence (:registry "*commands*" :source "systems/orchestrator-cli/graph-import.lisp"))
  (:command "--ιστορία" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--καθρέφτης" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--ρώτα" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :output-trust :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--σκέψεις" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :evolution :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--συμβόλαιο" :handler-file "systems/orchestrator-cli/self-reflection.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/self-reflection.lisp"))
  (:command "--σύνταγμα" :handler-file "systems/orchestrator-cli/decisions.lisp" :primitive :self :evidence (:registry "*commands*" :source "systems/orchestrator-cli/decisions.lisp"))
  (:command "--υπαγωγή" :handler-file "systems/orchestrator-cli/subsumption-commands.lisp" :primitive :proof :evidence (:registry "*commands*" :source "systems/orchestrator-cli/subsumption-commands.lisp"))
  (:command "--φάκελος" :handler-file "systems/orchestrator-cli/case-workspace.lisp" :primitive :matter :evidence (:registry "*commands*" :source "systems/orchestrator-cli/case-workspace.lisp"))
  (:command "-h" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
  (:command "-v" :handler-file "systems/orchestrator-cli/builtin-commands.lisp" :primitive :substrate :evidence (:registry "*commands*" :source "systems/orchestrator-cli/builtin-commands.lisp"))
 )
 :capabilities (
  (:capability "πρόσληψη-νομολογίας" :package "ORCHESTRATOR.CLI" :gate NIL :primitive :authority :evidence (:registry "self-model:all-capabilities"))
  (:capability "ταυτότητα-άρθρων" :package "ORCHESTRATOR.LEGAL-ID" :gate NIL :primitive :law :evidence (:registry "self-model:all-capabilities"))
  (:capability "αυτοεπίγνωση" :package "ORCHESTRATOR.SELF-MODEL" :gate "--mirror-gate" :primitive :self :evidence (:registry "self-model:all-capabilities"))
  (:capability "μάθηση-κατανόησης" :package "ORCHESTRATOR.CLI" :gate "--understanding-gate" :primitive :evolution :evidence (:registry "self-model:all-capabilities"))
  (:capability "σύμβουλος" :package "ORCHESTRATOR.CLI" :gate "--advisor-gate" :primitive :hypothesis :evidence (:registry "self-model:all-capabilities"))
  (:capability "διάλογος" :package "ORCHESTRATOR.COGNITION" :gate "--dialogue-gate" :primitive :self :evidence (:registry "self-model:all-capabilities"))
  (:capability "δεοντικό" :package "ORCHESTRATOR.DEONTIC" :gate "--deontic-gate" :primitive :law :evidence (:registry "self-model:all-capabilities"))
  (:capability "λογισμός-φραγμών" :package "ORCHESTRATOR.METAEVAL" :gate "--inference-gate" :primitive :proof :evidence (:registry "self-model:all-capabilities"))
  (:capability "συμπερασμός-wfs" :package "ORCHESTRATOR.INFERENCE" :gate "--inference-gate" :primitive :proof :evidence (:registry "self-model:all-capabilities"))
  (:capability "πυρήνας-iq" :package "ORCHESTRATOR.INFERENCE" :gate "--iq-gate" :primitive :proof :evidence (:registry "self-model:all-capabilities"))
  (:capability "ρευστή-επαγωγή" :package "ORCHESTRATOR.FLUID" :gate "--fluid-gate" :primitive :hypothesis :evidence (:registry "self-model:all-capabilities"))
  (:capability "ιστορία-συμβάντων" :package "ORCHESTRATOR.EVENTCALCULUS" :gate "--event-gate" :primitive :fact :evidence (:registry "self-model:all-capabilities"))
  (:capability "παραδοτέο" :package "ORCHESTRATOR.CLI" :gate "--draft-gate" :primitive :output-trust :evidence (:registry "self-model:all-capabilities"))
  (:capability "γλωσσική-αντίληψη" :package "ORCHESTRATOR.CASEGRAMMAR" :gate "--subsumption-gate" :primitive :fact :evidence (:registry "self-model:all-capabilities"))
  (:capability "υπαγωγή" :package "ORCHESTRATOR.SUBSUMPTION" :gate "--subsumption-gate" :primitive :proof :evidence (:registry "self-model:all-capabilities"))
  (:capability "αντιδικία" :package "ORCHESTRATOR.DIALECTIC" :gate "--subsumption-gate" :primitive :argument :evidence (:registry "self-model:all-capabilities"))
  (:capability "υποθετικός-λόγος" :package "ORCHESTRATOR.COUNTERFACTUAL" :gate "--subsumption-gate" :primitive :hypothesis :evidence (:registry "self-model:all-capabilities"))
  (:capability "δικονομικός-σχεδιασμός" :package "ORCHESTRATOR.STRATEGY" :gate "--subsumption-gate" :primitive :argument :evidence (:registry "self-model:all-capabilities"))
  (:capability "ομοιότητα-υποθέσεων" :package "ORCHESTRATOR.HYPO" :gate NIL :primitive :authority :evidence (:registry "self-model:all-capabilities"))
  (:capability "πακέτα-γνώσης" :package "ORCHESTRATOR.KNOWLEDGE-PACKS" :gate "--extension-gate" :primitive :memory :evidence (:registry "self-model:all-capabilities"))
  (:capability "αυτοεπέκταση" :package "ORCHESTRATOR.CLI" :gate "--extension-gate" :primitive :evolution :evidence (:registry "self-model:all-capabilities"))
  (:capability "πολιτικές-έγκρισης" :package "ORCHESTRATOR.CLI" :gate "--policy-gate" :primitive :institution :evidence (:registry "self-model:all-capabilities"))
  (:capability "μνήμη" :package "ORCHESTRATOR.MEMORY" :gate "--memory-gate" :primitive :memory :evidence (:registry "self-model:all-capabilities"))
  (:capability "γένεση-ελληνικών" :package "ORCHESTRATOR.GENERATION" :gate "--generation-gate" :primitive :output-trust :evidence (:registry "self-model:all-capabilities"))
  (:capability "εκτελεστική-προέλευση" :package "ORCHESTRATOR.TRACE" :gate "--provenance-gate" :primitive :output-trust :evidence (:registry "self-model:all-capabilities"))
  (:capability "ελεγχόμενη-αυτοεξέλιξη" :package "ORCHESTRATOR.ADOPTION" :gate "--self-evolution-gate" :primitive :evolution :evidence (:registry "self-model:all-capabilities"))
  (:capability "συστατικά" :package "ORCHESTRATOR.COMPONENTS" :gate "--component-gate" :primitive :self :evidence (:registry "self-model:all-capabilities"))
  (:capability "συμβόλαια" :package "ORCHESTRATOR.CONTRACTS" :gate "--contract-gate" :primitive :self :evidence (:registry "self-model:all-capabilities"))
 )
 :contracts (
  (:contract "institutional-identity" :kind :institutional-identity :capability "αυτοεπίγνωση" :tests ("--mirror-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "article-identity-management" :kind :protocol :capability "ταυτότητα-άρθρων" :tests ("--contract-gate" "--subsumption-gate" "--draft-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "understanding-rule-language" :kind :protocol :capability "μάθηση-κατανόησης" :tests ("--understanding-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "advisor-untrusted-protocol" :kind :protocol :capability "σύμβουλος" :tests ("--advisor-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "dialogue-protocol" :kind :protocol :capability "διάλογος" :tests ("--dialogue-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "evaluate-deontic" :kind :function :capability "δεοντικό" :tests ("--deontic-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "classify-deontic-sentence" :kind :function :capability "δεοντικό" :tests ("--deontic-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "meta-eval" :kind :function :capability "λογισμός-φραγμών" :tests ("--inference-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "guards-pass-p" :kind :function :capability "λογισμός-φραγμών" :tests ("--inference-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "verify-guard" :kind :function :capability "λογισμός-φραγμών" :tests ("--inference-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "run-inference" :kind :function :capability "συμπερασμός-wfs" :tests ("--inference-gate" "--iq-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "explain" :kind :function :capability "συμπερασμός-wfs" :tests ("--inference-gate" "--event-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "query" :kind :function :capability "συμπερασμός-wfs" :tests ("--inference-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "iq-referee-protocol" :kind :protocol :capability "πυρήνας-iq" :tests ("--iq-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "fluid-induction-protocol" :kind :protocol :capability "ρευστή-επαγωγή" :tests ("--fluid-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "event-calculus-protocol" :kind :protocol :capability "ιστορία-συμβάντων" :tests ("--event-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "draft-memo" :kind :function :capability "παραδοτέο" :tests ("--draft-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "gap-questions" :kind :function :capability "παραδοτέο" :tests ("--draft-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "parse-narrative" :kind :function :capability "γλωσσική-αντίληψη" :tests ("--subsumption-gate" "--dialogue-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "greek-perception-protocol" :kind :protocol :capability "γλωσσική-αντίληψη" :tests ("--subsumption-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "subsume" :kind :function :capability "υπαγωγή" :tests ("--subsumption-gate" "--draft-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "conclusion-status" :kind :function :capability "υπαγωγή" :tests ("--subsumption-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "norm-gaps" :kind :function :capability "υπαγωγή" :tests ("--subsumption-gate" "--draft-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "proof-grade" :kind :function :capability "υπαγωγή" :tests ("--subsumption-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "dialectic-report" :kind :function :capability "αντιδικία" :tests ("--subsumption-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "critical-facts" :kind :function :capability "υποθετικός-λόγος" :tests ("--subsumption-gate" "--draft-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "minimal-blockers" :kind :function :capability "υποθετικός-λόγος" :tests ("--subsumption-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "procedural-planning-protocol" :kind :protocol :capability "δικονομικός-σχεδιασμός" :tests ("--subsumption-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "knowledge-pack-lifecycle" :kind :protocol :capability "πακέτα-γνώσης" :tests ("--extension-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "self-extension-adoption" :kind :protocol :capability "αυτοεπέκταση" :tests ("--extension-gate" "--policy-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "approval-policy-protocol" :kind :protocol :capability "πολιτικές-έγκρισης" :tests ("--policy-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "episodic-memory-protocol" :kind :protocol :capability "μνήμη" :tests ("--memory-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "greek-generation-protocol" :kind :protocol :capability "γένεση-ελληνικών" :tests ("--generation-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "runtime-provenance-protocol" :kind :protocol :capability "εκτελεστική-προέλευση" :tests ("--provenance-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "adoption-decision-protocol" :kind :protocol :capability "ελεγχόμενη-αυτοεξέλιξη" :tests ("--self-evolution-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "component-registry-protocol" :kind :protocol :capability "συστατικά" :tests ("--component-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "parse-article-id" :kind :function :capability "ταυτότητα-άρθρων" :tests ("--component-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "contract-registry-protocol" :kind :protocol :capability "συμβόλαια" :tests ("--contract-gate") :evidence (:registry "contracts:all-contracts"))
  (:contract "mirror-protocol" :kind :protocol :capability "αυτοεπίγνωση" :tests ("--mirror-gate" "--contract-gate") :evidence (:registry "contracts:all-contracts"))
 )
)
