;;;; model-law-kernel.lisp — the small ARCHITECTURE-LAW KERNEL. Reads only internal, hash-pinned model files with
;;;; *read-eval* nil under with-standard-io-syntax (standard readtable; NO project reader macros; no eval, no
;;;; compilation of model content) and explicit size/depth/collection limits. Checks 7 model laws, returns typed
;;;; violations with causes+locations, exits non-zero on any unknown/malformed/violated law. NO regex/grep/substring
;;;; is structural proof. This is NOT semantic, legal, security, behavioral, operational or qualification proof.
(defpackage :aml-kernel (:use :cl))
(in-package :aml-kernel)
(load (merge-pathnames "sha256.lisp" *load-pathname*))
(defparameter +max-file-bytes+ 4000000) (defparameter +max-depth+ 40) (defparameter +max-list+ 20000)
(defvar *dir*) (defvar *facts* (make-hash-table :test 'equal)) (defvar *by-type* (make-hash-table :test 'equal))
(defvar *id-owner* (make-hash-table :test 'equal)) (defvar *ftypes* (make-hash-table :test 'equal))
(defvar *viol* '())
(defun v! (law reason loc) (push (list law reason loc) *viol*))
(defun sname (x) (cond ((symbolp x) (symbol-name x)) ((stringp x) x) (t (princ-to-string x))))
(defun kwname (x) (and (keywordp x) (symbol-name x)))
(defun fget (plist name) (loop for (k val) on plist by #'cddr when (and (keywordp k) (string-equal (kwname k) name)) return val))
(defun depth-ok (form d)                 ; walks cons cells; tolerates dotted/improper lists (e.g. :ref (k . target))
  (cond ((> d +max-depth+) nil)
        ((consp form)
         (let ((n 0) (cur form))
           (loop while (consp cur) do
             (incf n) (when (> n +max-list+) (return-from depth-ok nil))
             (unless (depth-ok (car cur) (1+ d)) (return-from depth-ok nil))
             (setf cur (cdr cur)))
           (depth-ok cur (1+ d))))
        (t t)))
(defun safe-read-forms (path)
  (when (> (with-open-file (s path :element-type '(unsigned-byte 8)) (file-length s)) +max-file-bytes+)
    (v! "L1" (format nil "file exceeds size limit") path) (return-from safe-read-forms nil))
  (with-standard-io-syntax
    (let ((*read-eval* nil) (*read-default-float-format* 'double-float) (out '()))
      (handler-case
          (with-open-file (s path :external-format :utf-8)
            (loop for f = (read s nil :eof) until (eq f :eof) do
              (unless (depth-ok f 0) (v! "L1" "form exceeds nesting/collection limit" path) (return))
              (push f out)))
        (error (e) (v! "L1" (format nil "unreadable model file (~a)" (type-of e)) path)))
      (nreverse out))))
(defun load-schema ()
  (dolist (form (safe-read-forms (merge-pathnames "MODEL-SCHEMA.sexp" *dir*)))
    (when (and (consp form) (string-equal (sname (car form)) "DEFINE-MODEL-SCHEMA"))
      (dolist (sub (cddr form))
        (when (and (consp sub) (string-equal (sname (car sub)) "DEFINE-FACT-TYPE"))
          (let* ((name (string-upcase (sname (second sub)))) (pl (cddr sub))
                 (req (mapcar #'sname (fget pl "REQUIRED")))
                 (refs (mapcar (lambda (r) (cons (string-upcase (sname (car r))) (string-upcase (sname (cdr r))))) (fget pl "REF"))))
            (setf (gethash name *ftypes*) (list req refs))))))))
(defun add-fact (type id plist loc)
  (let* ((tn (string-upcase (sname type))) (idn (sname id)) (key (cons tn idn)))
    (unless (gethash tn *ftypes*) (v! "L1" (format nil "undeclared fact type ~a" tn) loc))
    (when (nth-value 1 (gethash key *facts*)) (v! "L2" (format nil "duplicate seat ~a ~a" tn idn) loc))
    ;; global id uniqueness: an id may be owned by exactly one (type) — record first owner
    (let ((prev (gethash idn *id-owner*)))
      (when (and prev (not (string= prev tn))) (v! "L2" (format nil "id ~a declared under both ~a and ~a" idn prev tn) loc))
      (unless prev (setf (gethash idn *id-owner*) tn)))
    (setf (gethash key *facts*) plist) (push idn (gethash tn *by-type*))
    ;; required keys present (L1) + no duplicate key (single seat, L2)
    (let* ((spec (gethash tn *ftypes*)) (req (first spec)) (keys '()))
      (loop for (k val) on plist by #'cddr do
        (when (member (kwname k) keys :test #'string-equal) (v! "L2" (format nil "duplicate key ~a in ~a ~a" (kwname k) tn idn) loc))
        (push (kwname k) keys))
      (dolist (rk req) (unless (fget plist rk) (v! "L1" (format nil "~a ~a missing required key :~a" tn idn (string-downcase rk)) loc))))))
(defun root-module-names ()             ; single source of the module universe = ROOT.sexp composition (no dual list)
  (let ((root (car (safe-read-forms (merge-pathnames "ROOT.sexp" *dir*)))))
    (when (and (consp root) (string-equal (sname (car root)) "DEFINE-MODEL-ROOT"))
      (loop for entry in (fget (cddr root) "COMPOSITION") collect (fget entry "MODULE")))))
(defun load-facts ()
  (dolist (mod (root-module-names))     ; loads FACT forms from every pinned module; DEFINE-* forms are non-fact modules
    (dolist (form (safe-read-forms (merge-pathnames mod *dir*)))
      (cond ((and (consp form) (string-equal (sname (car form)) "FACT"))
             (if (>= (length form) 3) (add-fact (second form) (third form) (cdddr form) mod)
                 (v! "L1" "malformed fact (needs type+id)" mod)))
            ((and (consp form) (member (sname (car form)) '("DEFINE-MODEL-SCHEMA" "DEFINE-MODEL-ROOT" "DEFINE-TOOLCHAIN") :test #'string-equal)))
            (t (v! "L1" (format nil "unexpected top-level form in ~a" mod) mod))))))
(defun fact-exists (type id) (nth-value 1 (gethash (cons (string-upcase type) (sname id)) *facts*)))
(defun law3-closed-refs ()
  (maphash (lambda (key plist)
             (let* ((tn (car key)) (spec (gethash tn *ftypes*)) (refs (second spec)))
               (dolist (r refs)
                 (let ((val (fget plist (car r))))
                   (when (and val (not (fact-exists (cdr r) val)))
                     (v! "L3" (format nil "~a ~a: :~a -> undeclared ~a ~a" tn (cdr key) (string-downcase (car r)) (string-downcase (cdr r)) (sname val)) tn))))))
           *facts*))
(defun law4-acyclic ()
  (let ((adj (make-hash-table :test 'equal)) (color (make-hash-table :test 'equal)) (cyc nil))
    (maphash (lambda (key plist) (when (string= (car key) "STAGE-EDGE")
               (push (sname (fget plist "TO")) (gethash (sname (fget plist "FROM")) adj)))) *facts*)
    (labels ((dfs (u) (setf (gethash u color) :grey)
               (dolist (w (gethash u adj)) (case (gethash w color) (:grey (setf cyc u)) ((nil) (dfs w))))
               (setf (gethash u color) :black)))
      (dolist (s (gethash "STAGE" *by-type*)) (when (null (gethash s color)) (dfs s))))
    (when cyc (v! "L4" (format nil "cycle in permitted pipeline stage graph at ~a" cyc) "dependencies-and-boundaries.sexp"))))
(defun fact-plist (type id) (gethash (cons (string-upcase type) (sname id)) *facts*))
(defun classification (type id) (and (fact-exists type id) (sname (fget (fact-plist type id) "CLASSIFICATION"))))
(defun consumer-public-p (c)
  (cond ((fact-exists "SUBSYSTEM" c) (string-equal (classification "SUBSYSTEM" c) "PUBLIC"))
        ((fact-exists "COMPONENT" c) (let ((o (fget (fact-plist "COMPONENT" c) "OWNER-SUBSYSTEM"))) (string-equal (classification "SUBSYSTEM" o) "PUBLIC")))
        (t nil)))
(defun law5-isolation ()
  (maphash (lambda (key plist) (when (string= (car key) "CONSUMES")
             (let ((prov (sname (fget plist "PROVIDES"))) (cons (sname (fget plist "CONSUMER"))))
               (when (and (string-equal (classification "TYPE" prov) "PRIVATE") (consumer-public-p cons))
                 (v! "L5" (format nil "public/private leak: PUBLIC ~a consumes PRIVATE type ~a" cons prov) "dependencies-and-boundaries.sexp")))))
           *facts*))
(defun law6-reqmap ()
  (let ((covered (make-hash-table :test 'equal)))
    (maphash (lambda (key plist) (when (string= (car key) "REQ-MAP") (setf (gethash (sname (fget plist "SUBSYSTEM")) covered) t))) *facts*)
    (dolist (s (gethash "SUBSYSTEM" *by-type*)) (unless (gethash s covered)
      (v! "L6" (format nil "subsystem ~a has no requirement->seat->test->WP mapping" s) "requirements-tests-workpackets.sexp")))))
(defun law7-hash-universe ()
  (let* ((root (car (safe-read-forms (merge-pathnames "ROOT.sexp" *dir*)))) (declared '()))
    (unless (and (consp root) (string-equal (sname (car root)) "DEFINE-MODEL-ROOT"))
      (v! "L7" "ROOT.sexp missing define-model-root" "ROOT.sexp") (return-from law7-hash-universe))
    (dolist (entry (fget (cddr root) "COMPOSITION"))
      (let* ((name (fget entry "MODULE")) (pin (fget entry "SHA256")) (path (merge-pathnames name *dir*)))
        (push name declared)
        (if (probe-file path)
            (let ((actual (aml-sha:sha256-hex-of-file path)))
              (unless (string= actual pin) (v! "L7" (format nil "module ~a SHA drift (~a != pinned)" name (subseq actual 0 12)) name)))
            (v! "L7" (format nil "declared module ~a missing on disk" name) name))))
    ;; exact set: no EXTRA .sexp module in the dir beyond the declared set (+ ROOT itself)
    (dolist (f (directory (merge-pathnames "*.sexp" *dir*)))
      (let ((bn (file-namestring f)))
        (unless (or (string= bn "ROOT.sexp") (member bn declared :test #'string=))
          (v! "L7" (format nil "undeclared extra module on disk: ~a" bn) bn))))))
(defun main ()
  (setf *dir* (merge-pathnames "../" *load-pathname*))
  (let ((rootarg (second sb-ext:*posix-argv*))) (when rootarg (setf *dir* (make-pathname :directory (pathname-directory (truename rootarg))))))
  (load-schema) (load-facts)
  (law3-closed-refs) (law4-acyclic) (law5-isolation) (law6-reqmap) (law7-hash-universe)
  (setf *viol* (nreverse *viol*))
  (format t "~&; ARCHITECTURE-LAW KERNEL — facts=~a fact-types=~a~%" (hash-table-count *facts*) (hash-table-count *ftypes*))
  (if *viol*
      (progn (dolist (v *viol*) (format t "VIOLATION ~a: ~a  [~a]~%" (first v) (second v) (third v)))
             (format t "ARCHITECTURE MODEL LAWS: FAIL~%; (structural model-law check only — NOT semantic/legal/security/behavioral/operational/qualification proof)~%")
             (sb-ext:exit :code 3))
      (progn (format t "ARCHITECTURE MODEL LAWS: PASS~%; (structural model-law check only — NOT semantic/legal/security/behavioral/operational/qualification proof)~%")
             (sb-ext:exit :code 0))))
(main)
