;;;; model-law-kernel.lisp — the ARCHITECTURE-LAW KERNEL. Reads only internal, hash-pinned model files with
;;;; *read-eval* nil under with-standard-io-syntax (standard readtable; NO project reader macros; no eval, no
;;;; compilation of model content) and explicit size/depth/collection limits. Checks the model laws, returns typed
;;;; violations with causes+locations, exits non-zero on any unknown/malformed/violated law. NO regex/grep/substring
;;;; is structural proof. SHA-256 comes from a vetted external provider (KERNEL/hash-provider.lisp) over raw bytes;
;;;; there is no in-repo hash implementation and no fallback.
;;;; This is NOT semantic, legal, security, behavioral, operational or qualification proof.
(defpackage :aml-kernel (:use :cl))
(in-package :aml-kernel)
(load (merge-pathnames "hash-provider.lisp" *load-pathname*))
(defparameter +kernel-file+ *load-pathname*)
(defparameter +max-file-bytes+ 4000000) (defparameter +max-depth+ 40) (defparameter +max-list+ 60000)
(defvar *dir*) (defvar *facts* (make-hash-table :test 'equal)) (defvar *by-type* (make-hash-table :test 'equal))
(defvar *id-owner* (make-hash-table :test 'equal)) (defvar *ftypes* (make-hash-table :test 'equal))
(defvar *enums* (make-hash-table :test 'equal)) (defvar *renders* '()) (defvar *viol* '())
(defun v! (law reason loc) (push (list law reason loc) *viol*))
(defun sname (x) (cond ((symbolp x) (symbol-name x)) ((stringp x) x) (t (princ-to-string x))))
(defun kwname (x) (and (keywordp x) (symbol-name x)))
(defun fget (plist name) (loop for (k val) on plist by #'cddr when (and (keywordp k) (string-equal (kwname k) name)) return val))
(defun plain-symbol-name-p (s)
  (and (plusp (length s))
       (every (lambda (c) (or (char<= #\A c #\Z) (char<= #\0 c #\9) (find c "_.+/-"))) s)))
(defun vrender (v)                      ; the ONE canonical value rendering (see MODEL-SCHEMA.sexp); NIL = illegal kind
  (cond ((stringp v) v)
        ((integerp v) (princ-to-string v))
        ((and v (symbolp v) (not (keywordp v)) (plain-symbol-name-p (symbol-name v))) (symbol-name v))
        (t nil)))
(defun depth-ok (form d)                 ; walks cons cells; tolerates improper lists defensively
  (cond ((> d +max-depth+) nil)
        ((consp form)
         (let ((n 0) (cur form))
           (loop while (consp cur) do
             (incf n) (when (> n +max-list+) (return-from depth-ok nil))
             (unless (depth-ok (car cur) (1+ d)) (return-from depth-ok nil))
             (setf cur (cdr cur)))
           (depth-ok cur (1+ d))))
        (t t)))
(defun safe-read-forms (path)
  (when (> (with-open-file (s path :element-type '(unsigned-byte 8)) (file-length s)) +max-file-bytes+)
    (v! "L1" (format nil "file exceeds size limit") path) (return-from safe-read-forms nil))
  (with-standard-io-syntax
    (let ((*read-eval* nil) (*read-default-float-format* 'double-float) (out '()))
      (handler-case
          (with-open-file (s path :external-format :utf-8)
            (loop for f = (read s nil :eof) until (eq f :eof) do
              (unless (depth-ok f 0) (v! "L1" "form exceeds nesting/collection limit" path) (return))
              (push f out)))
        (error (e) (v! "L1" (format nil "unreadable model file (~a)" (type-of e)) path)))
      (nreverse out))))
(defun load-schema ()
  (dolist (form (safe-read-forms (merge-pathnames "MODEL-SCHEMA.sexp" *dir*)))
    (when (and (consp form) (string-equal (sname (car form)) "DEFINE-MODEL-SCHEMA"))
      (dolist (sub (cddr form))
        (when (consp sub)
          (cond
            ((string-equal (sname (car sub)) "DEFINE-ENUM")
             (setf (gethash (string-upcase (sname (second sub))) *enums*)
                   (mapcar (lambda (x) (string-upcase (sname x))) (third sub))))
            ((string-equal (sname (car sub)) "DEFINE-FACT-TYPE")
             (let* ((name (string-upcase (sname (second sub)))) (pl (cddr sub))
                    (req (mapcar #'sname (fget pl "REQUIRED")))
                    (enums (mapcar (lambda (r) (cons (string-upcase (sname (first r))) (string-upcase (sname (second r)))))
                                   (fget pl "ENUM")))
                    (refs (mapcar (lambda (r) (cons (string-upcase (sname (car r)))
                                                    (mapcar (lambda (x) (string-upcase (sname x))) (cdr r))))
                                  (fget pl "REF"))))
               (setf (gethash name *ftypes*) (list req refs enums))))))))))
(defun add-fact (type id plist loc)
  (let* ((tn (string-upcase (sname type))) (idn (vrender id)) (key (cons tn (or idn (sname id)))))
    (unless idn (v! "L1" (format nil "~a: illegal id value kind" tn) loc) (setf idn (sname id)))
    (unless (gethash tn *ftypes*) (v! "L1" (format nil "undeclared fact type ~a" tn) loc))
    (when (nth-value 1 (gethash key *facts*)) (v! "L2" (format nil "duplicate seat ~a ~a" tn idn) loc))
    (let ((prev (gethash idn *id-owner*)))
      (when (and prev (not (string= prev tn))) (v! "L2" (format nil "id ~a declared under both ~a and ~a" idn prev tn) loc))
      (unless prev (setf (gethash idn *id-owner*) tn)))
    (setf (gethash key *facts*) plist) (push idn (gethash tn *by-type*))
    (let* ((spec (gethash tn *ftypes*)) (req (first spec)) (enums (third spec)) (keys '()) (pairs '()))
      (loop for (k val) on plist by #'cddr do
        (let ((kn (kwname k)))
          (unless kn (v! "L1" (format nil "~a ~a: non-keyword plist key" tn idn) loc) (return))
          (when (member kn keys :test #'string-equal) (v! "L2" (format nil "duplicate key ~a in ~a ~a" kn tn idn) loc))
          (push kn keys)
          (let ((vr (vrender val)))
            (if (null vr)
                (v! "L1" (format nil "~a ~a: :~a has an illegal value kind (permitted: string, integer, plain symbol)"
                                 tn idn (string-downcase kn)) loc)
                (progn
                  (push (format nil "~a=~a" (string-upcase kn) vr) pairs)
                  (let ((ed (cdr (assoc kn enums :test #'string-equal))))
                    (when ed
                      (let ((dom (gethash ed *enums*)))
                        (cond ((null dom) (v! "L1" (format nil "~a ~a: :~a cites undeclared enum ~a"
                                                          tn idn (string-downcase kn) ed) loc))
                              ((not (member (string-upcase vr) dom :test #'string=))
                               (v! "L1" (format nil "~a ~a: :~a = ~a is outside enum ~a domain {~{~a~^ ~}}"
                                                tn idn (string-downcase kn) vr (string-downcase ed) dom) loc)))))))))))
      (dolist (rk req) (unless (fget plist rk) (v! "L1" (format nil "~a ~a missing required key :~a" tn idn (string-downcase rk)) loc)))
      (push (list loc tn (format nil "~a|~a|~{~a~^|~}" tn idn (sort pairs #'string<))) *renders*))))
(defun root-form () (car (safe-read-forms (merge-pathnames "ROOT.sexp" *dir*))))
(defun root-composition ()              ; single source of the module universe = ROOT.sexp composition, in order
  (let ((root (root-form)))
    (when (and (consp root) (string-equal (sname (car root)) "DEFINE-MODEL-ROOT"))
      (loop for entry in (fget (cddr root) "COMPOSITION") collect (cons (fget entry "MODULE") (fget entry "SHA256"))))))
(defun load-facts ()
  (dolist (mod (mapcar #'car (root-composition)))
    (dolist (form (safe-read-forms (merge-pathnames mod *dir*)))
      (cond ((and (consp form) (string-equal (sname (car form)) "FACT"))
             (if (>= (length form) 3) (add-fact (second form) (third form) (cdddr form) mod)
                 (v! "L1" "malformed fact (needs type+id)" mod)))
            ((and (consp form) (member (sname (car form)) '("DEFINE-MODEL-SCHEMA" "DEFINE-MODEL-ROOT" "DEFINE-TOOLCHAIN") :test #'string-equal)))
            (t (v! "L1" (format nil "unexpected top-level form in ~a" mod) mod))))))
(defun fact-exists (type id) (nth-value 1 (gethash (cons (string-upcase type) (sname id)) *facts*)))
(defun law3-closed-refs ()
  (maphash (lambda (key plist)
             (let* ((tn (car key)) (spec (gethash tn *ftypes*)) (refs (second spec)))
               (dolist (r refs)
                 (let ((val (fget plist (car r))))
                   (when val
                     (let ((vr (or (vrender val) (sname val))))
                       (unless (some (lambda (tgt) (fact-exists tgt vr)) (cdr r))
                         (v! "L3" (format nil "~a ~a: :~a = ~a resolves to no declared ~{~a~^ or ~}"
                                          tn (cdr key) (string-downcase (car r)) vr (mapcar #'string-downcase (cdr r)))
                             tn))))))))
           *facts*))
(defun edge-relations ()                ; every declared FROM/TO relation over one node type is an acyclicity duty
  (let ((out '()))
    (maphash (lambda (tn spec)
               (let* ((refs (second spec)) (f (assoc "FROM" refs :test #'string=)) (tt (assoc "TO" refs :test #'string=)))
                 (when (and f tt (= 1 (length (cdr f))) (equal (cdr f) (cdr tt)))
                   (push (cons tn (first (cdr f))) out))))
             *ftypes*)
    out))
(defun law4-acyclic ()
  (dolist (rel (edge-relations))
    (let ((adj (make-hash-table :test 'equal)) (color (make-hash-table :test 'equal)) (cyc nil))
      (maphash (lambda (key plist) (when (string= (car key) (car rel))
                 (push (sname (fget plist "TO")) (gethash (sname (fget plist "FROM")) adj)))) *facts*)
      (labels ((dfs (u) (setf (gethash u color) :grey)
                 (dolist (w (gethash u adj)) (case (gethash w color) (:grey (setf cyc u)) ((nil) (dfs w))))
                 (setf (gethash u color) :black)))
        (dolist (s (gethash (cdr rel) *by-type*)) (when (null (gethash s color)) (dfs s))))
      (when cyc (v! "L4" (format nil "cycle in the ~a graph over ~a at ~a"
                                 (string-downcase (car rel)) (string-downcase (cdr rel)) cyc) (car rel))))))
(defun fact-plist (type id) (gethash (cons (string-upcase type) (sname id)) *facts*))
(defun classification (type id) (and (fact-exists type id) (sname (fget (fact-plist type id) "CLASSIFICATION"))))
(defun consumer-kind (c)                ; :public | :private | :unpermitted | :unknown — never a silent "not public"
  (cond ((fact-exists "SUBSYSTEM" c) (if (string= (classification "SUBSYSTEM" c) "PUBLIC") :public :private))
        ((fact-exists "COMPONENT" c)
         (let ((o (sname (fget (fact-plist "COMPONENT" c) "OWNER-SUBSYSTEM"))))
           (cond ((not (fact-exists "SUBSYSTEM" o)) :unknown)
                 ((string= (classification "SUBSYSTEM" o) "PUBLIC") :public)
                 (t :private))))
        ;; a type may consume only when it declares an explicit consumer-role (the proposer class)
        ((fact-exists "TYPE" c)
         (if (fget (fact-plist "TYPE" c) "CONSUMER-ROLE")
             (if (string= (classification "TYPE" c) "PUBLIC") :public :private)
             :unpermitted))
        (t :unknown)))
(defun law5-isolation ()
  (maphash (lambda (key plist) (when (string= (car key) "CONSUMES")
             (let* ((prov (sname (fget plist "PROVIDES"))) (cns (sname (fget plist "CONSUMER"))) (kind (consumer-kind cns)))
               (case kind
                 (:unknown (v! "L5" (format nil "consumer ~a of ~a is of unknown kind — isolation cannot be decided" cns prov)
                               "dependencies-and-boundaries.sexp"))
                 (:unpermitted (v! "L5" (format nil "type ~a is used as a consumer of ~a but declares no :consumer-role" cns prov)
                                   "dependencies-and-boundaries.sexp"))
                 (:public (when (string= (classification "TYPE" prov) "PRIVATE")
                            (v! "L5" (format nil "public/private leak: PUBLIC ~a consumes PRIVATE type ~a" cns prov)
                                "dependencies-and-boundaries.sexp")))))))
           *facts*))
(defun law6-reqmap ()
  (let ((covered (make-hash-table :test 'equal)))
    (maphash (lambda (key plist) (declare (ignore key)) plist) *facts*)
    (maphash (lambda (key plist) (when (string= (car key) "REQ-MAP") (setf (gethash (sname (fget plist "SUBSYSTEM")) covered) t))) *facts*)
    (dolist (s (gethash "SUBSYSTEM" *by-type*)) (unless (gethash s covered)
      (v! "L6" (format nil "subsystem ~a has no requirement->seat->test->WP mapping" s) "requirements-tests-workpackets.sexp")))))
(defun law7-hash-universe ()
  (let* ((root (root-form)) (comp (root-composition)) (declared '()) (rows '()))
    (unless (and (consp root) (string-equal (sname (car root)) "DEFINE-MODEL-ROOT"))
      (v! "L7" "ROOT.sexp missing define-model-root" "ROOT.sexp") (return-from law7-hash-universe))
    (dolist (entry comp)
      (let* ((name (car entry)) (pin (cdr entry)) (path (merge-pathnames name *dir*)))
        (push name declared)
        (if (probe-file path)
            (let ((actual (aml-hash:sha256-hex-of-file path)))
              (push (format nil "~a:~a" name actual) rows)
              (unless (string= actual pin) (v! "L7" (format nil "module ~a SHA drift (~a != pinned)" name (subseq actual 0 12)) name)))
            (progn (push (format nil "~a:MISSING" name) rows)
                   (v! "L7" (format nil "declared module ~a missing on disk" name) name)))))
    (dolist (f (directory (merge-pathnames "*.sexp" *dir*)))
      (let ((bn (file-namestring f)))
        (unless (or (string= bn "ROOT.sexp") (member bn declared :test #'string=))
          (v! "L7" (format nil "undeclared extra module on disk: ~a" bn) bn))))
    (let ((recomputed (aml-hash:sha256-hex-of-string (format nil "~{~a~^~%~}" (nreverse rows))))
          (stated (fget (cddr root) "CANONICAL-MODEL-ROOT-DIGEST"))
          (cnt (fget (cddr root) "MODULE-COUNT")))
      (unless (and (integerp cnt) (= cnt (length comp)))
        (v! "L7" (format nil "declared :module-count ~a != ~a pinned modules" cnt (length comp)) "ROOT.sexp"))
      (unless (equal recomputed (sname stated))
        (v! "L7" (format nil "canonical-model-root-digest mismatch: recomputed ~a != declared ~a"
                         (subseq recomputed 0 16) (subseq (sname stated) 0 16)) "ROOT.sexp")))))
(defun repo-root ()
  (let ((d (pathname-directory (truename (make-pathname :name nil :type nil :defaults +kernel-file+)))))
    (dotimes (i 7) (setf d (butlast d)))
    (make-pathname :directory d :name nil :type nil :version nil)))
(defun init-hash-provider ()
  (let ((decl nil))
    (dolist (form (safe-read-forms (merge-pathnames "TOOLCHAIN.sexp" *dir*)))
      (when (and (consp form) (string-equal (sname (car form)) "DEFINE-TOOLCHAIN"))
        (dolist (sub (cddr form))
          (when (and (consp sub) (string-equal (sname (car sub)) "HASH-PROVIDER")) (setf decl (second sub))))))
    (unless decl
      (format t "~&TOOLCHAIN-FAILURE: TOOLCHAIN.sexp declares no (:hash-provider ...)~%")
      (format t "SHA-256 PROVIDER: UNAVAILABLE — no model hash was computed and no verdict is issued.~%")
      (finish-output) (sb-ext:exit :code 4))
    (aml-hash:ensure-provider (merge-pathnames (sname (fget decl "SOURCE-REGISTRY-TREE")) (repo-root))
                              (sname (fget decl "SYSTEM-NAME"))
                              (sname (fget (fget decl "SEMANTIC-REQUIREMENT") "VERSION")))))
(defun commitment-lines ()
  (let ((mods (make-hash-table :test 'equal)) (fams (make-hash-table :test 'equal)) (all '()) (out '()))
    (dolist (r *renders*)
      (push (third r) all) (push (third r) (gethash (first r) mods)) (push (third r) (gethash (second r) fams)))
    (flet ((dig (l) (aml-hash:sha256-hex-of-string (format nil "~{~a~^~%~}" (sort (copy-list l) #'string<)))))
      (push (format nil "COMMITMENT total-facts ~a" (length all)) out)
      (push (format nil "COMMITMENT total-digest ~a" (dig all)) out)
      (dolist (m (sort (loop for k being the hash-keys of mods collect k) #'string<))
        (push (format nil "COMMITMENT module ~a ~a ~a" m (length (gethash m mods)) (dig (gethash m mods))) out))
      (dolist (f (sort (loop for k being the hash-keys of fams collect k) #'string<))
        (push (format nil "COMMITMENT family ~a ~a ~a" (string-downcase f) (length (gethash f fams)) (dig (gethash f fams))) out)))
    (nreverse out)))
(defun main ()
  (setf *dir* (merge-pathnames "../" *load-pathname*))
  (let ((rootarg (second sb-ext:*posix-argv*))) (when rootarg (setf *dir* (make-pathname :directory (pathname-directory (truename rootarg))))))
  (init-hash-provider)
  (load-schema) (load-facts)
  (law3-closed-refs) (law4-acyclic) (law5-isolation) (law6-reqmap) (law7-hash-universe)
  (setf *viol* (nreverse *viol*))
  (let ((lines (commitment-lines)))
    (with-open-file (s (merge-pathnames "KERNEL-COMMITMENT.txt" *dir*)
                       :direction :output :if-exists :supersede :if-does-not-exist :create :external-format :utf-8)
      (dolist (l lines) (write-line l s)))
    (dolist (l lines) (format t "~a~%" l)))
  (format t "~&; ARCHITECTURE-LAW KERNEL — facts=~a fact-types=~a enums=~a hash-provider=~a~%"
          (hash-table-count *facts*) (hash-table-count *ftypes*) (hash-table-count *enums*) (aml-hash:provider-id))
  (if *viol*
      (progn (dolist (v *viol*) (format t "VIOLATION ~a: ~a  [~a]~%" (first v) (second v) (third v)))
             (format t "ARCHITECTURE MODEL LAWS: FAIL~%; (structural model-law check only — NOT semantic/legal/security/behavioral/operational/qualification proof)~%")
             (sb-ext:exit :code 3))
      (progn (format t "ARCHITECTURE MODEL LAWS: PASS~%; (structural model-law check only — NOT semantic/legal/security/behavioral/operational/qualification proof)~%")
             (sb-ext:exit :code 0))))
(main)
